Added WeatherMgr::rollNewWeather
zeldaret/botw pull request #100
Opened 2022-08-06 14:08 UTC by savage13

- Added `WeatherMgr::rollNewWeather`
- Changed `WeatherType` to `u8`
   - Changed 1st arg of `Manager::setWeatherType` to `u32`
   - Changed 1st arg of `Manager::getWeatherTypeString` to `u32`

2022-08-06 18:14 UTC, leoetlino requested changes
> Reviewed 2 of 6 files at r1, 5 of 5 files at r2, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/zeldaret/botw/100)* status: all files reviewed, 19 unresolved discussions (waiting on @savage13)

___
*[`src/KingSystem/ActorSystem/actInfoData.cpp` line 745 at r2](https://reviewable.io/reviews/zeldaret/botw/100#-N8oLh-Y99E7JJ2tJou_:-N8oLh-Y99E7JJ2tJoua:b-aotvze) ([raw file](https://github.com/zeldaret/botw/blob/2882b7e816ac382124a970ba64ca6f42ccac0a00/src/KingSystem/ActorSystem/actInfoData.cpp#L745)):*
> ```cpp
>     }
>     auto current_weather = world::WeatherType(world::Manager::instance()->sub_71010F337C(pos));
>     const char* current_weather_name = world::Manager::getWeatherTypeString(u32(current_weather));
> ```

Can we add an overload of getWeatherTypeString that takes in a WeatherType, casts it to u32 and calls the u32 overload?
___
*[`src/KingSystem/World/worldManager.h` line 213 at r4](https://reviewable.io/reviews/zeldaret/botw/100#-N8oIaQ887hXBxF4i15X:-N8oIaQ94WQntcnShHxV:bfqrefl) ([raw file](https://github.com/zeldaret/botw/blob/b54096c57517beda49a1c59fb8cb2aaaac5a9311/src/KingSystem/World/worldManager.h#L213)):*
> ```objc
>     u8 sub_71010F337C(const sead::Vector3f& pos);  // TODO implement this : 0x71010F337C - maybe has
>                                                    // a different parameter type
>     WorldInfo* getWorldInfo() { return &mWorldInfo; }
> ```

Is this used?
___
*[`src/KingSystem/World/worldManager.cpp` line 71 at r2](https://reviewable.io/reviews/zeldaret/botw/100#-N8oLsNx2twte8O8KaPt:-N8oLsNx2twte8O8KaPu:bsadl74) ([raw file](https://github.com/zeldaret/botw/blob/2882b7e816ac382124a970ba64ca6f42ccac0a00/src/KingSystem/World/worldManager.cpp#L71)):*
> ```cpp
> void Manager::setWeatherType(u32 weather_type, bool x, bool y, bool for_demo) {
>     // Ignore invalid weather requests.
>     if (weather_type >= u32(NumWeatherTypes))
> ```

Cast not required, as NumWeatherTypes is already a u32.
___
*[`src/KingSystem/World/worldManager.cpp` line 80 at r2](https://reviewable.io/reviews/zeldaret/botw/100#-N8oLxM9BugKPn_DQXiS:-N8oLxM9BugKPn_DQXiT:b29bncq) ([raw file](https://github.com/zeldaret/botw/blob/2882b7e816ac382124a970ba64ca6f42ccac0a00/src/KingSystem/World/worldManager.cpp#L80)):*
> ```cpp
>         return;
> 
>     mWeatherType.mValue = u8(weather_type);
> ```

I think you might be able to turn mWeatherType into a WeatherType (instead of a SizedEnum).
___
*[`src/KingSystem/World/worldManager.cpp` line 89 at r2](https://reviewable.io/reviews/zeldaret/botw/100#-N8oM52j5RjbR3faNOhn:-N8oM52j5RjbR3faNOho:btnkrdk) ([raw file](https://github.com/zeldaret/botw/blob/2882b7e816ac382124a970ba64ca6f42ccac0a00/src/KingSystem/World/worldManager.cpp#L89)):*
> ```cpp
>     for (u8 i = 0; i < NumWeatherTypes; ++i) {
>         if (weather_type == cWeatherTypes[i]) {
>             setWeatherType(u32(WeatherType(i)), x, y, for_demo);
> ```

just `i` should be enough
___
*[`src/KingSystem/World/worldManager.cpp` line 97 at r2](https://reviewable.io/reviews/zeldaret/botw/100#-N8oMCI04g0RMJnKd_ZJ:-N8oMCI04g0RMJnKd_ZK:bgfhd5l) ([raw file](https://github.com/zeldaret/botw/blob/2882b7e816ac382124a970ba64ca6f42ccac0a00/src/KingSystem/World/worldManager.cpp#L97)):*
> ```cpp
> const char* Manager::getWeatherTypeString(u32 type) {
>     auto index = s32(type);
>     if (u32(index) >= NumWeatherTypes)
> ```

What if you just use `type` directly? It's already a u32.
___
*[`src/KingSystem/World/worldWeatherMgr.h` line 10 at r4](https://reviewable.io/reviews/zeldaret/botw/100#-N8oIsI7-8wMjW-oi870:-N8oIsI7-8wMjW-oi871:b-m9m3wd) ([raw file](https://github.com/zeldaret/botw/blob/b54096c57517beda49a1c59fb8cb2aaaac5a9311/src/KingSystem/World/worldWeatherMgr.h#L10)):*
> ```objc
> 
> struct ClimateWeathers {
>     s32 weather[20];
> ```

What is 20? What kind of value does this store?
___
*[`src/KingSystem/World/worldWeatherMgr.h` line 11 at r4](https://reviewable.io/reviews/zeldaret/botw/100#-N8oIj5_Ca6TzQVtgfEs:-N8oIj5_Ca6TzQVtgfEt:bpshfan) ([raw file](https://github.com/zeldaret/botw/blob/b54096c57517beda49a1c59fb8cb2aaaac5a9311/src/KingSystem/World/worldWeatherMgr.h#L11)):*
> ```objc
> struct ClimateWeathers {
>     s32 weather[20];
>     // int _4[20];
> ```

This should probably be removed?
___
*[`src/KingSystem/World/worldWeatherMgr.h` line 32 at r4](https://reviewable.io/reviews/zeldaret/botw/100#-N8oInxY1lHeiHE9uyEa:-N8oInxY1lHeiHE9uyEb:bpl5emu) ([raw file](https://github.com/zeldaret/botw/blob/b54096c57517beda49a1c59fb8cb2aaaac5a9311/src/KingSystem/World/worldWeatherMgr.h#L32)):*
> ```objc
>     u8 _20[0x24 - 0x20];
>     float _24;
>     u8 weather;
> ```

WeatherType?
___
*[`src/KingSystem/World/worldWeatherMgr.h` line 34 at r4](https://reviewable.io/reviews/zeldaret/botw/100#-N8oJ0J71bqyBb1ESf2K:-N8oJ0J71bqyBb1ESf2L:btaqa40) ([raw file](https://github.com/zeldaret/botw/blob/b54096c57517beda49a1c59fb8cb2aaaac5a9311/src/KingSystem/World/worldWeatherMgr.h#L34)):*
> ```objc
>     u8 weather;
>     u8 _29;
>     u8 _2a[20 * 18];
> ```

another occurrence of the 20 magic number -- can you introduce a named constant?
___
*[`src/KingSystem/World/worldWeatherMgr.h` line 36 at r4](https://reviewable.io/reviews/zeldaret/botw/100#-N8oJ4930tuj97CCBjg3:-N8oJ4930tuj97CCBjg4:bl8toyg) ([raw file](https://github.com/zeldaret/botw/blob/b54096c57517beda49a1c59fb8cb2aaaac5a9311/src/KingSystem/World/worldWeatherMgr.h#L36)):*
> ```objc
>     u8 _2a[20 * 18];
>     u8 _193;
>     struct ClimateWeathers climateWeathers[3];  // 0x194
> ```

* `struct` is unnecessary in C++
* consider adding a named constant for 3
* this should be called mClimateWeathers
___
*[`src/KingSystem/World/worldWeatherMgr.h` line 40 at r4](https://reviewable.io/reviews/zeldaret/botw/100#-N8oJK-L44wqCgfjUH8q:-N8oJK-L44wqCgfjUH8r:b-ttt79d) ([raw file](https://github.com/zeldaret/botw/blob/b54096c57517beda49a1c59fb8cb2aaaac5a9311/src/KingSystem/World/worldWeatherMgr.h#L40)):*
> ```objc
>     float mTimeBlock;  // 0x318
>     u32 mWeekDay;      // 0x31c
>     u8 _31C[0x398 - 0x320];
> ```

`_31c`
___
*[`src/KingSystem/World/worldWeatherMgr.cpp` line 28 at r2](https://reviewable.io/reviews/zeldaret/botw/100#-N8oK3Kd8ux01RgZjT3f:-N8oK3Ke4DXK6CFnyoa1:bes1vx6) ([raw file](https://github.com/zeldaret/botw/blob/2882b7e816ac382124a970ba64ca6f42ccac0a00/src/KingSystem/World/worldWeatherMgr.cpp#L28)):*
> ```cpp
> 
>     bool isWaterRelicRainOn = envMgr->isWaterRelicRainOn(climate);
>     bool value = false;
> ```

Is it possible to separate the water relic check and the glider flag stuff? Currently the two checks run into each other and it's not very readable. I also feel like it should be possible to get rid of the isWaterRelicRainOn variable and use the result of envMgr-³isWaterRelicRainOn() directly (ditto for gliderHandle)
___
*[`src/KingSystem/World/worldWeatherMgr.cpp` line 38 at r2](https://reviewable.io/reviews/zeldaret/botw/100#-N8oL2N8Ami3aVkC7SkE:-N8oL2N8Ami3aVkC7SkF:b-h7ajxj) ([raw file](https://github.com/zeldaret/botw/blob/2882b7e816ac382124a970ba64ca6f42ccac0a00/src/KingSystem/World/worldWeatherMgr.cpp#L38)):*
> ```cpp
>     } else {
>         hasParaglider = false;
>     }
> ```

a line break here would make this more readable
___
*[`src/KingSystem/World/worldWeatherMgr.cpp` line 40 at r2](https://reviewable.io/reviews/zeldaret/botw/100#-N8oL5Zj2uTgXeJOUIuV:-N8oL5Zj2uTgXeJOUIuW:bovkzjm) ([raw file](https://github.com/zeldaret/botw/blob/2882b7e816ac382124a970ba64ca6f42ccac0a00/src/KingSystem/World/worldWeatherMgr.cpp#L40)):*
> ```cpp
>     }
>     auto result = weather;
>     if (weather == WeatherType::Bluesky || weather == WeatherType::Cloudy || hasParaglider)
> ```

This is kind of confusing, because result is already equal to weather. Consider:

```
if (weather != BlueSky && weather != Cloudy && !hasParaglider)
    return Bluesky;
return weather;
```

Or:

```
if (weather == BlueSky || weather == Cloudy || hasParaglider)
    return weather;
retur [...]

2022-08-07 21:25 UTC, savage13 reviewed
> *[Reviewable](https://reviewable.io/reviews/zeldaret/botw/100)* status: 4 of 8 files reviewed, 19 unresolved discussions (waiting on @leoetlino)

___
*[`src/KingSystem/ActorSystem/actInfoData.cpp` line 745 at r2](https://reviewable.io/reviews/zeldaret/botw/100#-N8oLh-Y99E7JJ2tJou_:-N8trzgg12ZuCK1dLzhb:b-z5yn8d) ([raw file](https://github.com/zeldaret/botw/blob/2882b7e816ac382124a970ba64ca6f42ccac0a00/src/KingSystem/ActorSystem/actInfoData.cpp#L745)):*
<details><summary><i>Previously, leoetlino (Léo Lam) wrote…</i></summary><blockquote>

Can we add an overload of getWeatherTypeString that takes in a WeatherType, casts it to u32 and calls the u32 overload?
</blockquote></details>

Done.  The call in `actInfoData.cpp:InvalidLifeConditions()` looks appears to want a u32 before the function call to `getWeatherTypeString()` .
___
*[`src/KingSystem/World/worldManager.h` line 213 at r4](https://reviewable.io/reviews/zeldaret/botw/100#-N8oIaQ887hXBxF4i15X:-N8tvEiS3volR8wD6R7q:b56e70v) ([raw file](https://github.com/zeldaret/botw/blob/b54096c57517beda49a1c59fb8cb2aaaac5a9311/src/KingSystem/World/worldManager.h#L213)):*
<details><summary><i>Previously, leoetlino (Léo Lam) wrote…</i></summary><blockquote>

Is this used?
</blockquote></details>

It will be in the future.  I will remove it and add it when it is needed.
___
*[`src/KingSystem/World/worldManager.cpp` line 71 at r2](https://reviewable.io/reviews/zeldaret/botw/100#-N8oLsNx2twte8O8KaPt:-N8tvc5R7qdGysfzzTDU:b-896fix) ([raw file](https://github.com/zeldaret/botw/blob/2882b7e816ac382124a970ba64ca6f42ccac0a00/src/KingSystem/World/worldManager.cpp#L71)):*
<details><summary><i>Previously, leoetlino (Léo Lam) wrote…</i></summary><blockquote>

Cast not required, as NumWeatherTypes is already a u32.
</blockquote></details>

Done.
___
*[`src/KingSystem/World/worldManager.cpp` line 80 at r2](https://reviewable.io/reviews/zeldaret/botw/100#-N8oLxM9BugKPn_DQXiS:-N8twCo70XMhCt1kLaJp:b-bwhads) ([raw file](https://github.com/zeldaret/botw/blob/2882b7e816ac382124a970ba64ca6f42ccac0a00/src/KingSystem/World/worldManager.cpp#L80)):*
<details><summary><i>Previously, leoetlino (Léo Lam) wrote…</i></summary><blockquote>

I think you might be able to turn mWeatherType into a WeatherType (instead of a SizedEnum).
</blockquote></details>

Done.  Please check the casts from u32 to WeatherType() are ok.
___
*[`src/KingSystem/World/worldManager.cpp` line 89 at r2](https://reviewable.io/reviews/zeldaret/botw/100#-N8oM52j5RjbR3faNOhn:-N8twZmj5Eo0rrwBZsah:b-896fix) ([raw file](https://github.com/zeldaret/botw/blob/2882b7e816ac382124a970ba64ca6f42ccac0a00/src/KingSystem/World/worldManager.cpp#L89)):*
<details><summary><i>Previously, leoetlino (Léo Lam) wrote…</i></summary><blockquote>

just `i` should be enough
</blockquote></details>

Done.
___
*[`src/KingSystem/World/worldManager.cpp` line 97 at r2](https://reviewable.io/reviews/zeldaret/botw/100#-N8oMCI04g0RMJnKd_ZJ:-N8twwLp6NvGKiZAgfrr:b-9ep6so) ([raw file](https://github.com/zeldaret/botw/blob/2882b7e816ac382124a970ba64ca6f42ccac0a00/src/KingSystem/World/worldManager.cpp#L97)):*
<details><summary><i>Previously, leoetlino (Léo Lam) wrote…</i></summary><blockquote>

What if you just use `type` directly? It's already a u32.
</blockquote></details>

Removing the line 
`auto index = s32(type);` and only using `type` results in:

`TARGET            |        CURRENT (200)`
`10f2d88:    sxtw    x8, w0                        | fbefdc:    mov     w8, w0`
___
*[`src/KingSystem/World/worldWeatherMgr.h` line 10 at r4](https://reviewable.io/reviews/zeldaret/botw/100#-N8oIsI7-8wMjW-oi870:-N8tybuwDLKbvMjigBkf:b-gw0zaj) ([raw file](https://github.com/zeldaret/botw/blob/b54096c57517beda49a1c59fb8cb2aaaac5a9311/src/KingSystem/World/worldWeatherMgr.h#L10)):*
<details><summary><i>Previously, leoetlino (Léo Lam) wrote…</i></summary><blockquote>

What is 20? What kind of value does this store?
</blockquote></details>

This looks like ClimateWeathers based on `loadInfo()`.  Can I leave a note like "This may be incorrect"?
___
*[`src/KingSystem/World/worldWeatherMgr.h` line 11 at r4](https://reviewable.io/reviews/zeldaret/botw/100#-N8oIj5_Ca6TzQVtgfEs:-N8txoVF510t1A-hodSe:b-896fix) ([raw file](https://github.com/zeldaret/botw/blob/b54096c57517beda49a1c59fb8cb2aaaac5a9311/src/KingSystem/World/worldWeatherMgr.h#L11)):*
<details><summary><i>Previously, leoetlino (Léo Lam) wrote…</i></summary><blockquote>

This should probably be removed?
</blockquote></details>

Done.
___
*[`src/KingSystem/World/worldWeatherMgr.h` line 32 at r4](https://reviewable.io/reviews/zeldaret/botw/100#-N8oInxY1lHeiHE9uyEa:-N8u91Zr-pSwKvzrbZmk:b-2pke46) ([raw file](https://github.com/zeldaret/botw/blob/b54096c57517beda49a1c59fb8cb2aaaac5a9311/src/KingSystem/World/worldWeatherMgr.h#L32)):*
<details><summary><i>Previously, leoetlino (Léo Lam) wrote…</i></summary><blockquote>

WeatherType?
</blockquote></details>

Probably, but I am not sure.  
___
*[`src/KingSystem/World/worldWeatherMgr.h` line 34 at r4](https://reviewable.io/reviews/zeldaret/botw/100#-N8oJ0J71bqyBb1ESf2K:-N8tyse4C3VJoCpa2rcs:bijajn1) ([raw file](https://github.com/zeldaret/botw/blob/b54096c57517beda49a1c59fb8cb2aaaac5a9311/src/KingSystem/World/worldWeatherMgr.h#L34)):*
<details><summary><i>Previously, leoetlino (Léo Lam) wrote…</i></summary><blockquote>

another occurrence of the 20 magic number -- can you introduce a named constant?
</blockquote></details>

Changed to NumClimates NumWeatherCycles * 6, but I am unsure what the 6 is for. The 3 may refer to the Number of  Weather Cycles.    
___
*[`src/KingSystem/World/worldWeatherMgr.h` line 36 at r4](https://reviewable.io/reviews/zeldaret/botw/100#-N8oJ4930tuj97CCBjg3:-N8u2Hf94F8M4SvwQbqc:bb6un1j) ([raw file](https://github.com/zeldaret/botw/blob/b54096c57517beda49a1c59fb8cb2aaaac5a9311/src/KingSystem/World/worldWeatherMgr.h#L36)):*
<details><summary><i>Previously, leoetlino (Léo Lam) wrote…</i></summary><blockquote>

* `struct` is unnecessary in C++
* consider adding a named constant for 3
* this should be called mClimateWeathers
</blockquote></details>

Done
___
*[`src/KingSystem/World/worldWeatherMgr.h` line 40 at r4](https://reviewable.io/reviews/zeldaret/botw/100#-N8oJK-L44wqCgfjUH8q:-N8u2LCI-pRxmreak5O2:b-896fix) ([raw file](https://github.com/zeldaret/botw/blob/b54096c57517beda49a1c59fb8cb2aaaac5a9311/src/KingSystem/World/worldWeatherMgr.h#L40)):*
<details><summary><i>Previously, leoetlino (Léo Lam) wrote…</i></summary><blockquote>

`_31c`
</blockquote></details>

Done.
___
*[`src/KingSystem/World/worldWeatherMgr.cpp` line 28 at r2](https://reviewable.io/reviews/zeldaret/botw/100#-N8oK3Kd8ux01RgZjT3f:-N8u6th82RjehtB2JxiV:b-896fix) ([raw file](https://github.com/zeldaret/botw/blob/2882b7e816ac382124a970ba64ca6f42ccac0a00/src/KingSystem/World/worldWeatherMgr.cpp#L28)):*
<details><summary><i>Previously, leoetlino (Léo Lam) wrote…</i></summary><blockquote>

Is it possible to separate the water relic check and the glider flag stuff? Currently the two checks run into each other and it's not very readable. I also feel like it should be possible to get rid of the isWaterRelicRainOn variable and use the result of envMgr-³isWaterRelicRainOn() directly (ditto for gliderHandle)
</blockquote></details>

Done.
___
*[`src/KingSystem/World/worldWeatherMgr.cpp` line 38 at r2](https://reviewable.io/reviews/zeldaret/botw/100#-N8oL2N8Ami3aVkC7SkE:-N8u33w64NPeFNIOpPVz:b-896fix) ([raw file](https://github.com/zeldaret/botw/blob/2882b7e816ac382124a970ba64ca6f42ccac0a00/src/KingSystem/World/worldWeatherMgr.cpp#L38)):*
<details><summary><i>Previously, leoetlino (Léo Lam) wrote…</i></summary><blockquote>

a line break here would make this more readable
</blockquote></details>

Done.
___
*[`src/KingSystem/World/worldWeatherMgr.cpp` line 40 at r2](https://reviewable.io/reviews/zeldaret/botw/100#-N8oL5Zj2uTgXeJOUIuV:-N8u3QpYByJ1BW6pdyJu:biu4flv) ([raw file](https://github.com/zeldaret/botw/blob/2882b7e816ac382124a970ba64ca6f42ccac0a00/s [...]

2022-08-07 22:31 UTC, leoetlino reviewed
> Reviewed 4 of 4 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/zeldaret/botw/100)* status: all files reviewed, 8 unresolved discussions (waiting on @savage13)

___
*[`src/KingSystem/ActorSystem/actInfoData.cpp` line 745 at r2](https://reviewable.io/reviews/zeldaret/botw/100#-N8oLh-Y99E7JJ2tJou_:-N8uQW9rAIGyOGF_U1et:b-c2cncf) ([raw file](https://github.com/zeldaret/botw/blob/2882b7e816ac382124a970ba64ca6f42ccac0a00/src/KingSystem/ActorSystem/actInfoData.cpp#L745)):*
<details><summary><i>Previously, savage13 wrote…</i></summary><blockquote>

Done.  The call in `actInfoData.cpp:InvalidLifeConditions()` looks appears to want a u32 before the function call to `getWeatherTypeString()` .
</blockquote></details>

I'd make the `getWeatherTypeString(WeatherType)` overload inline so that the casting happens on the caller side (e.g. in this actInfoData function) rather than in worldManager.cpp
___
*[`src/KingSystem/World/worldManager.cpp` line 97 at r2](https://reviewable.io/reviews/zeldaret/botw/100#-N8oMCI04g0RMJnKd_ZJ:-N8uPU4OBF1BUlHK-aSP:b-3ox3ry) ([raw file](https://github.com/zeldaret/botw/blob/2882b7e816ac382124a970ba64ca6f42ccac0a00/src/KingSystem/World/worldManager.cpp#L97)):*
<details><summary><i>Previously, savage13 wrote…</i></summary><blockquote>

Removing the line 
`auto index = s32(type);` and only using `type` results in:

`TARGET            |        CURRENT (200)`
`10f2d88:    sxtw    x8, w0                        | fbefdc:    mov     w8, w0`


</blockquote></details>

Interesting, this u32 -> s32 > u32 casting should be a no-op :thinking:  oh well
___
*[`src/KingSystem/World/worldWeatherMgr.h` line 10 at r4](https://reviewable.io/reviews/zeldaret/botw/100#-N8oIsI7-8wMjW-oi870:-N8uPg7n1863Z9q58IVy:bb74ce2) ([raw file](https://github.com/zeldaret/botw/blob/b54096c57517beda49a1c59fb8cb2aaaac5a9311/src/KingSystem/World/worldWeatherMgr.h#L10)):*
<details><summary><i>Previously, savage13 wrote…</i></summary><blockquote>

This looks like ClimateWeathers based on `loadInfo()`.  Can I leave a note like "This may be incorrect"?
</blockquote></details>

Sure
___
*[`src/KingSystem/World/worldWeatherMgr.h` line 32 at r4](https://reviewable.io/reviews/zeldaret/botw/100#-N8oInxY1lHeiHE9uyEa:-N8uPowJ5uA6xFdosthM:b54rs0c) ([raw file](https://github.com/zeldaret/botw/blob/b54096c57517beda49a1c59fb8cb2aaaac5a9311/src/KingSystem/World/worldWeatherMgr.h#L32)):*
<details><summary><i>Previously, savage13 wrote…</i></summary><blockquote>

Probably, but I am not sure.  
</blockquote></details>

Might be worth adding a comment in that case
___
*[`src/KingSystem/World/worldWeatherMgr.h` line 11 at r5](https://reviewable.io/reviews/zeldaret/botw/100#-N8uPiYs0ZZ_U-5h2T6o:-N8uPiYs0ZZ_U-5h2T6p:b-kjil6t) ([raw file](https://github.com/zeldaret/botw/blob/5d445c168aff809c8a2a2315b434171cc8b2f85f/src/KingSystem/World/worldWeatherMgr.h#L11)):*
> ```objc
> constexpr u32 NumWeatherCycles = 3;
> 
> class ClimateWeathers {
> ```

I'd make this a struct as it only contains data
___
*[`src/KingSystem/World/worldWeatherMgr.cpp` line 27 at r5](https://reviewable.io/reviews/zeldaret/botw/100#-N8uQ3UADoRC4Ve56JlV:-N8uQ3UADoRC4Ve56JlW:bi5frnj) ([raw file](https://github.com/zeldaret/botw/blob/5d445c168aff809c8a2a2315b434171cc8b2f85f/src/KingSystem/World/worldWeatherMgr.cpp#L27)):*
> ```cpp
> 
>     auto* env_mgr = wm->getEnvMgr();
>     bool isWaterRelicRainOn = env_mgr->isWaterRelicRainOn(climate);
> ```

`if (env_mgr->...)` -- no need for an extra variable.
___
*[`src/KingSystem/World/worldWeatherMgr.cpp` line 33 at r5](https://reviewable.io/reviews/zeldaret/botw/100#-N8uQCZC0Kq1x3iheQXO:-N8uQCZDBuvpWTsqSePM:bt28qxh) ([raw file](https://github.com/zeldaret/botw/blob/5d445c168aff809c8a2a2315b434171cc8b2f85f/src/KingSystem/World/worldWeatherMgr.cpp#L33)):*
> ```cpp
>     bool plateau_done = false;
>     bool has_paraglider = false;
>     auto gliderHandle = Manager::instance()->getTimeMgr()->isGetPlayerStole2Flag();
> ```

glider_handle
___
*[`src/KingSystem/World/worldWeatherMgr.cpp` line 35 at r5](https://reviewable.io/reviews/zeldaret/botw/100#-N8uQBmb6KDHTLNg1p0G:-N8uQBmb6KDHTLNg1p0H:bdi9zc8) ([raw file](https://github.com/zeldaret/botw/blob/5d445c168aff809c8a2a2315b434171cc8b2f85f/src/KingSystem/World/worldWeatherMgr.cpp#L35)):*
> ```cpp
>     auto gliderHandle = Manager::instance()->getTimeMgr()->isGetPlayerStole2Flag();
>     if (gliderHandle != gdt::InvalidHandle) {
>         gdt::Manager::instance()->getBool(gliderHandle, &plateau_done, true);
> ```

nit: I think it would make more sense to pass has_paraglider
___
*[`src/KingSystem/World/worldWeatherMgr.cpp` line 36 at r5](https://reviewable.io/reviews/zeldaret/botw/100#-N8uQFMJ4pbldmlkxBb3:-N8uQFMJ4pbldmlkxBb4:bgzbx6o) ([raw file](https://github.com/zeldaret/botw/blob/5d445c168aff809c8a2a2315b434171cc8b2f85f/src/KingSystem/World/worldWeatherMgr.cpp#L36)):*
> ```cpp
>     if (gliderHandle != gdt::InvalidHandle) {
>         gdt::Manager::instance()->getBool(gliderHandle, &plateau_done, true);
>         has_paraglider = plateau_done;
> ```

...and then this would become `plateau_done = has_paraglider;`


<!-- Sent from Reviewable.io -->

2022-08-07 23:04 UTC, savage13 reviewed
> *[Reviewable](https://reviewable.io/reviews/zeldaret/botw/100)* status: 3 of 8 files reviewed, 8 unresolved discussions (waiting on @leoetlino)

___
*[`src/KingSystem/ActorSystem/actInfoData.cpp` line 745 at r2](https://reviewable.io/reviews/zeldaret/botw/100#-N8oLh-Y99E7JJ2tJou_:-N8uXj7cDKIFjyX-FWtz:b-2dabcb) ([raw file](https://github.com/zeldaret/botw/blob/2882b7e816ac382124a970ba64ca6f42ccac0a00/src/KingSystem/ActorSystem/actInfoData.cpp#L745)):*
<details><summary><i>Previously, leoetlino (Léo Lam) wrote…</i></summary><blockquote>

I'd make the `getWeatherTypeString(WeatherType)` overload inline so that the casting happens on the caller side (e.g. in this actInfoData function) rather than in worldManager.cpp
</blockquote></details>

Done. That one took at bit. Needed to move it into the header file to move the cast into actInfoData.cpp.  :)
___
*[`src/KingSystem/World/worldWeatherMgr.h` line 10 at r4](https://reviewable.io/reviews/zeldaret/botw/100#-N8oIsI7-8wMjW-oi870:-N8uUQJH6yGIUWb1gwMV:b-896fix) ([raw file](https://github.com/zeldaret/botw/blob/b54096c57517beda49a1c59fb8cb2aaaac5a9311/src/KingSystem/World/worldWeatherMgr.h#L10)):*
<details><summary><i>Previously, leoetlino (Léo Lam) wrote…</i></summary><blockquote>

Sure
</blockquote></details>

Done.
___
*[`src/KingSystem/World/worldWeatherMgr.h` line 32 at r4](https://reviewable.io/reviews/zeldaret/botw/100#-N8oInxY1lHeiHE9uyEa:-N8uUW_o49_NsUjOi6a_:b-896fix) ([raw file](https://github.com/zeldaret/botw/blob/b54096c57517beda49a1c59fb8cb2aaaac5a9311/src/KingSystem/World/worldWeatherMgr.h#L32)):*
<details><summary><i>Previously, leoetlino (Léo Lam) wrote…</i></summary><blockquote>

Might be worth adding a comment in that case
</blockquote></details>

Done.
___
*[`src/KingSystem/World/worldWeatherMgr.h` line 11 at r5](https://reviewable.io/reviews/zeldaret/botw/100#-N8uPiYs0ZZ_U-5h2T6o:-N8uUQcB4wDArsZWnWgU:b-896fix) ([raw file](https://github.com/zeldaret/botw/blob/5d445c168aff809c8a2a2315b434171cc8b2f85f/src/KingSystem/World/worldWeatherMgr.h#L11)):*
<details><summary><i>Previously, leoetlino (Léo Lam) wrote…</i></summary><blockquote>

I'd make this a struct as it only contains data
</blockquote></details>

Done.
___
*[`src/KingSystem/World/worldWeatherMgr.cpp` line 27 at r5](https://reviewable.io/reviews/zeldaret/botw/100#-N8uQ3UADoRC4Ve56JlV:-N8uUkGC1ZlzugEUaqDV:b-896fix) ([raw file](https://github.com/zeldaret/botw/blob/5d445c168aff809c8a2a2315b434171cc8b2f85f/src/KingSystem/World/worldWeatherMgr.cpp#L27)):*
<details><summary><i>Previously, leoetlino (Léo Lam) wrote…</i></summary><blockquote>

`if (env_mgr->...)` -- no need for an extra variable.
</blockquote></details>

Done.
___
*[`src/KingSystem/World/worldWeatherMgr.cpp` line 33 at r5](https://reviewable.io/reviews/zeldaret/botw/100#-N8uQCZC0Kq1x3iheQXO:-N8uUtxL4XhH-1aAF609:b-896fix) ([raw file](https://github.com/zeldaret/botw/blob/5d445c168aff809c8a2a2315b434171cc8b2f85f/src/KingSystem/World/worldWeatherMgr.cpp#L33)):*
<details><summary><i>Previously, leoetlino (Léo Lam) wrote…</i></summary><blockquote>

glider_handle
</blockquote></details>

Done.
___
*[`src/KingSystem/World/worldWeatherMgr.cpp` line 35 at r5](https://reviewable.io/reviews/zeldaret/botw/100#-N8uQBmb6KDHTLNg1p0G:-N8uV2ui3RHeKhW9VM-t:b-896fix) ([raw file](https://github.com/zeldaret/botw/blob/5d445c168aff809c8a2a2315b434171cc8b2f85f/src/KingSystem/World/worldWeatherMgr.cpp#L35)):*
<details><summary><i>Previously, leoetlino (Léo Lam) wrote…</i></summary><blockquote>

nit: I think it would make more sense to pass has_paraglider
</blockquote></details>

Done.
___
*[`src/KingSystem/World/worldWeatherMgr.cpp` line 36 at r5](https://reviewable.io/reviews/zeldaret/botw/100#-N8uQFMJ4pbldmlkxBb3:-N8uVE8A-_4sVcNA2CgN:b-896fix) ([raw file](https://github.com/zeldaret/botw/blob/5d445c168aff809c8a2a2315b434171cc8b2f85f/src/KingSystem/World/worldWeatherMgr.cpp#L36)):*
<details><summary><i>Previously, leoetlino (Léo Lam) wrote…</i></summary><blockquote>

...and then this would become `plateau_done = has_paraglider;`
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-08-07 23:58 UTC, leoetlino reviewed
> Reviewed 5 of 5 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/zeldaret/botw/100)* status: all files reviewed, 2 unresolved discussions (waiting on @savage13)

___
*[`src/KingSystem/World/worldManager.h` line 102 at r6](https://reviewable.io/reviews/zeldaret/botw/100#-N8uii-xBPDeHkxoCk_e:-N8uii-xBPDeHkxoCk_f:b-6vvlbh) ([raw file](https://github.com/zeldaret/botw/blob/376c9ce4271c89be874f94df0d23c02c247f3b0d/src/KingSystem/World/worldManager.h#L102)):*
> ```objc
>     void setWeatherType(const sead::SafeString& weather_type, bool x, bool y, bool for_demo);
>     static const char* getWeatherTypeString(u32 type);
>     inline static const char* getWeatherTypeString(WeatherType type) {
> ```

No need for `inline` -- class member functions defined inside the class definition are already implicitly inline, and the only other reason for which you might want to use the `inline` specifier (telling Clang to use a higher inline cost threshold) doesn't apply here because the function is so small it will almost always be inlined even if you don't nudge Clang into doing it.
___
*[`src/KingSystem/World/worldWeatherMgr.h` line 11 at r6](https://reviewable.io/reviews/zeldaret/botw/100#-N8ujI1o6a7x7OiL9jIg:-N8ujI1o6a7x7OiL9jIh:b2ni7nk) ([raw file](https://github.com/zeldaret/botw/blob/376c9ce4271c89be874f94df0d23c02c247f3b0d/src/KingSystem/World/worldWeatherMgr.h#L11)):*
> ```objc
> constexpr u32 NumWeatherCycles = 3;
> 
> // This make be incorrect
> ```

may
___
*[`src/KingSystem/World/worldWeatherMgr.cpp` line 36 at r5](https://reviewable.io/reviews/zeldaret/botw/100#-N8uQFMJ4pbldmlkxBb3:-N8ujWwg7wCY6r1GPaeo:b-8m3mlh) ([raw file](https://github.com/zeldaret/botw/blob/5d445c168aff809c8a2a2315b434171cc8b2f85f/src/KingSystem/World/worldWeatherMgr.cpp#L36)):*
<details><summary><i>Previously, savage13 wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Oh nice, so this matches without the second boolean variable


<!-- Sent from Reviewable.io -->

2022-08-08 10:28 UTC, savage13 reviewed
> *[Reviewable](https://reviewable.io/reviews/zeldaret/botw/100)* status: all files reviewed, 2 unresolved discussions (waiting on @leoetlino)

___
*[`src/KingSystem/World/worldManager.h` line 102 at r6](https://reviewable.io/reviews/zeldaret/botw/100#-N8uii-xBPDeHkxoCk_e:-N8wz_b5-kMkyXNne192:b-896fix) ([raw file](https://github.com/zeldaret/botw/blob/376c9ce4271c89be874f94df0d23c02c247f3b0d/src/KingSystem/World/worldManager.h#L102)):*
<details><summary><i>Previously, leoetlino (Léo Lam) wrote…</i></summary><blockquote>

No need for `inline` -- class member functions defined inside the class definition are already implicitly inline, and the only other reason for which you might want to use the `inline` specifier (telling Clang to use a higher inline cost threshold) doesn't apply here because the function is so small it will almost always be inlined even if you don't nudge Clang into doing it.
</blockquote></details>

Done.
___
*[`src/KingSystem/World/worldWeatherMgr.h` line 11 at r6](https://reviewable.io/reviews/zeldaret/botw/100#-N8ujI1o6a7x7OiL9jIg:-N8wzdVHEKB42sgJobc9:b-896fix) ([raw file](https://github.com/zeldaret/botw/blob/376c9ce4271c89be874f94df0d23c02c247f3b0d/src/KingSystem/World/worldWeatherMgr.h#L11)):*
<details><summary><i>Previously, leoetlino (Léo Lam) wrote…</i></summary><blockquote>

may
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-08-08 10:31 UTC, leoetlino approved these changes
> Reviewed 2 of 2 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/zeldaret/botw/100)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @savage13)



<!-- Sent from Reviewable.io -->

2022-08-08 10:35 UTC, merged