resPlacement
zeldaret/botw pull request #120
Opened 2023-06-07 23:34 UTC by Esras

First project PR, hopefully I followed the right standards.

Adds the ksys::res::Placement class. I do think I'm missing two functions, but working on adding them and wanted feedback on where this was right now.

2023-06-07 23:42 UTC, notyourav commented
*[`src/KingSystem/Resource/resPlacement.h` line 17 at r1](https://reviewable.io/reviews/zeldaret/botw/120#-NXNE8PJ2R6rgRRtbjq5:-NXNE8PJ2R6rgRRtbjq6:b-sp7f4m) ([raw file](https://github.com/zeldaret/botw/blob/912821c10aad933d3c122a654c3f6a765b09ed5e/src/KingSystem/Resource/resPlacement.h#L17)):*
> ```objc
>     void registerFactory(sead::Heap* heap);
> 
>     long mVar1;
> ```

I would make these s32


<!-- Sent from Reviewable.io -->

2023-06-07 23:43 UTC, notyourav reviewed
> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/zeldaret/botw/120)* status: all files reviewed, 1 unresolved discussion (waiting on @Esras)



<!-- Sent from Reviewable.io -->

2023-06-08 19:29 UTC, leoetlino requested changes
taking a look at the vtables, it looks like there are a few functions you have reimplemented but not listed in the CSV:

- F42740 is res::Placement::checkDerivedRuntimeTypeInfo
  - F42804 (the function which is called by checkDerivedRuntimeTypeInfo) is res::Placement::checkDerivedRuntimeTypeInfoStatic
- F42748 is res::Placement::getRuntimeTypeInfo
- F427A4 is res::Placement::~Placement (the D0 deleting destructor; refer to https://botw.link/contribute/cpp-primer#virtual-destructors if you're not sure what that means)
- F427C8 is res::Placement::doCreate_ (okay, looks like the two members are definitely pointers)
- F427D4 is a non-virtual thunk to res::Placement::~Placement
- F427DC is the same (but a thunk to the D0 destructor)

you should take a look at the vtable of `res::EntryFactory<res::Placement>` to ensure you list all of its functions in the CSV (you get all of those functions generated for you for free, would be a shame not to make the decompiled code% higher :P)

> Reviewed 4 of 4 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/zeldaret/botw/120#-:-NXRSndZDpssuvGZrm4q:bhjtntx)* status: all files reviewed, 4 unresolved discussions (waiting on @Esras and @notyourav)

___
*[`src/KingSystem/Resource/resPlacement.h` line 15 at r1](https://reviewable.io/reviews/zeldaret/botw/120#-NXRSUvJ2Usaabgr4Lj3:-NXRSUvJ2Usaabgr4Lj4:b-z23je8) ([raw file](https://github.com/zeldaret/botw/blob/912821c10aad933d3c122a654c3f6a765b09ed5e/src/KingSystem/Resource/resPlacement.h#L15)):*
> ```objc
>     ~Placement() override;
> 
>     void registerFactory(sead::Heap* heap);
> ```

It'd make more sense for this to be a static member function
___
*[`src/KingSystem/Resource/resPlacement.h` line 17 at r1](https://reviewable.io/reviews/zeldaret/botw/120#-NXNE8PJ2R6rgRRtbjq5:-NXRSIfs1CoB34p7-nl3:bu76hwt) ([raw file](https://github.com/zeldaret/botw/blob/912821c10aad933d3c122a654c3f6a765b09ed5e/src/KingSystem/Resource/resPlacement.h#L17)):*
<details><summary><i>Previously, notyourav wrote…</i></summary><blockquote>

I would make these s32
</blockquote></details>

long is 64-bit, not 32-bit. I think these are probably pointers - not sure what type though, so I'd just make them void* (e.g. `void* mUnk = nullptr;`)
___
*[`src/KingSystem/Resource/resPlacement.cpp` line 16 at r1](https://reviewable.io/reviews/zeldaret/botw/120#-NXRSbj54QAOL6_uaFVI:-NXRSbj54QAOL6_uaFVJ:b-o09o3t) ([raw file](https://github.com/zeldaret/botw/blob/912821c10aad933d3c122a654c3f6a765b09ed5e/src/KingSystem/Resource/resPlacement.cpp#L16)):*
> ```cpp
> 
>     res::registerEntryFactory(new (heap) EntryFactory<Placement>(1.0, sizeof(Placement)),
>                               "bPlacement");
> ```

bplacement?
___
*[`src/KingSystem/Resource/resPlacement.cpp` line 19 at r1](https://reviewable.io/reviews/zeldaret/botw/120#-NXRSP3K4Q-zqvuaXpSl:-NXRSP3LCGKzgejw9t8a:b-9svq62) ([raw file](https://github.com/zeldaret/botw/blob/912821c10aad933d3c122a654c3f6a765b09ed5e/src/KingSystem/Resource/resPlacement.cpp#L19)):*
> ```cpp
> }
> 
> Placement::Placement() {
> ```

this can just be `Placement::Placement() = default;` after the above comment is addressed


<!-- Sent from Reviewable.io -->

2023-06-08 19:30 UTC, leoetlino commented
tip: run `tools/listsym res::Placement` and you'll see if there are any symbols that you may have missed and not declared in the CSV

2023-06-09 18:26 UTC, Esras commented
Thanks for the detailed feedback!

I think I got thrown off because there's the VTable for the Placement struct, the EntryFactory<Placement> struct, and then one more for just the Placement destructors, it seems? I might be missing one more because I'm not sure where the `ksys::res::EntryFactory<ksys::res::Placement>::checkDerivedRuntimeTypeInfo` function is and I can't seem to find where the registerFactory function would live (I'm not sure it does, the registration seems to live in `res::ResourceMgrTask::init()` (F38D5C).

2023-06-11 19:34 UTC, leoetlino reviewed
> Reviewed 3 of 3 files at r3.
> *[Reviewable](https://reviewable.io/reviews/zeldaret/botw/120)* status: 2 of 4 files reviewed, all discussions resolved (waiting on @Esras)



<!-- Sent from Reviewable.io -->

2023-06-11 19:41 UTC, leoetlino commented
* 0x0000007100f427c8 should have the mangled name of ksys::res::Placement::doCreate_ listed
* 0x0000007100f427d4 is not doDestroy, it's a non-virtual thunk to the D1/D2 destructor (this exists because ksys::res::Resource uses multiple inheritance)
* 0x0000007100f427dc is a non-virtual thunk to the D0 destructor

You'll find the correct symbols to use for the non-virtual thunks by running `tools/listsym res::Placement`

>  I might be missing one more because I'm not sure where the `ksys::res::EntryFactory<ksys::res::Placement>::checkDerivedRuntimeTypeInfo` function is

I think that's 0x0000007100f4259c. Sometimes checkDerivedRuntimeTypeInfoStatic gets inlined, which means you'll only see checkDerivedRuntimeTypeInfo.

> and I can't seem to find where the registerFactory function would live (I'm not sure it does, the registration seems to live in res::ResourceMgrTask::init() (F38D5C).

Yeah, I'm not sure registerFactory actually exists. As you've noticed, the registration is done in res::ResourceMgrTask. I think it's fine to keep registerFactory for the time being to force the compiler to emit the res::Placement and EntryFactory functions.

2023-06-11 19:55 UTC, leoetlino commented on data/uking_functions.csv
> +0x0000007100f4259c,W,000132,_ZN4ksys3res12EntryFactoryINS0_9PlacementEE33checkDerivedRuntimeTypeInfoStaticEPKN4sead15RuntimeTypeInfo9InterfaceE
checkDerivedRuntimeTypeInfo, notcheckDerivedRuntimeTypeInfoStatic

2023-06-11 22:13 UTC, leoetlino approved these changes

2023-06-11 22:16 UTC, leoetlino approved these changes
> Reviewed 2 of 2 files at r4, 1 of 1 files at r5, 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/zeldaret/botw/120)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @Esras)



<!-- Sent from Reviewable.io -->

2023-06-11 22:17 UTC, merged