AirOctaFlyUp::handleMessage ok, AirOctaFlyUp::leave_ not ok with a difference of 0
zeldaret/botw pull request #121
Opened 2023-06-10 03:31 UTC by bomba1749

2023-06-14 01:43 UTC, bomba1749 commented
I've decompiled AirOctaFlyUp functions handleMessage_, enter_, and leave_. I've also decompiled the AirOctaDataMgr function sub_71002fb17c (to be named), which is in /game right now because i dont know where the proper location for it would be.
Also, AirOctaFlyUp::loadParams_ now doesnt match with a difference of 0, because it expects a void at a specific line, and another function needs an AirOctaDataMgr** there. I'm sure that it's an easy fix, but I dont know how to fix it :P

also sorry about having so many commits in this, all that's changed in a lot of them is that i updated the cmake lists or the decompiled functions csv. All you really need to check is /game/ai/AI/aiAirOctaFlyUp.cpp and .h, and /game/AirOctaDataMgrTemp.cpp and .h.

2023-07-03 02:12 UTC, bomba1749 commented
I've decompiled AirOctaFlyUp functions handleMessage_, enter_, and leave_, and calc, which is nearly complete but still has 2 instructions that are different. I've also decompiled the AirOctaDataMgr function sub_71002fb17c (to be named), which is in /game right now because i dont know where the proper location for it would be.

2023-07-08 22:56 UTC, leoetlino requested changes
> Reviewed 12 of 13 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/zeldaret/botw/121)* status: 12 of 13 files reviewed, 38 unresolved discussions (waiting on @bomba1749)

___
*[`src/Game/AirOctaDataMgrTemp.h` line 2 at r1](https://reviewable.io/reviews/zeldaret/botw/121#-NZrb79k7qiCKhSr_k-T:-NZrb79k7qiCKhSr_k-U:bwjeect) ([raw file](https://github.com/zeldaret/botw/blob/2bb7c1ee40a060cc487de0475bc81eec2d6fc247/src/Game/AirOctaDataMgrTemp.h#L2)):*
> ```objc
> #pragma once
> #include "KingSystem/ActorSystem/actActor.h"
> ```

please add empty lines (one after the pragma and another after the include)
___
*[`src/Game/AirOctaDataMgrTemp.h` line 3 at r1](https://reviewable.io/reviews/zeldaret/botw/121#-NZrbDOy5vU-N38hCv1z:-NZrbDOy5vU-N38hCv2-:b4pptwn) ([raw file](https://github.com/zeldaret/botw/blob/2bb7c1ee40a060cc487de0475bc81eec2d6fc247/src/Game/AirOctaDataMgrTemp.h#L3)):*
> ```objc
> #pragma once
> #include "KingSystem/ActorSystem/actActor.h"
> namespace uking {
> ```

add an empty line below
___
*[`src/Game/AirOctaDataMgrTemp.h` line 5 at r1](https://reviewable.io/reviews/zeldaret/botw/121#-NZrbI_w7jLzTcuAwqKO:-NZrbI_xEciwynIrrgs9:brttjp) ([raw file](https://github.com/zeldaret/botw/blob/2bb7c1ee40a060cc487de0475bc81eec2d6fc247/src/Game/AirOctaDataMgrTemp.h#L5)):*
> ```objc
> namespace uking {
> class AirOctaDataMgr {
>     SEAD_RTTI_BASE(AirOctaDataMgr)
> ```

add `#include <prim/seadRuntimeTypeInfo.h>` (you should include what you use and avoid indirect includes)
___
*[`src/Game/AirOctaDataMgrTemp.h` line 6 at r1](https://reviewable.io/reviews/zeldaret/botw/121#-NZrbxTAEriANv2M8p3s:-NZrbxTAEriANv2M8p3t:ber4rhy) ([raw file](https://github.com/zeldaret/botw/blob/2bb7c1ee40a060cc487de0475bc81eec2d6fc247/src/Game/AirOctaDataMgrTemp.h#L6)):*
> ```objc
> class AirOctaDataMgr {
>     SEAD_RTTI_BASE(AirOctaDataMgr)
> public:
> ```

I'd recommend using this type definition as it's more complete compared to yours: https://discord.com/channels/688807550715560050/745633101157498880/1124088376123994142
___
*[`src/Game/AirOctaDataMgrTemp.h` line 21 at r1](https://reviewable.io/reviews/zeldaret/botw/121#-NZrbF1REyu1pFOJt22j:-NZrbF1REyu1pFOJt22k:b4pptwn) ([raw file](https://github.com/zeldaret/botw/blob/2bb7c1ee40a060cc487de0475bc81eec2d6fc247/src/Game/AirOctaDataMgrTemp.h#L21)):*
> ```objc
>     /*0x118 */ float unk_118;
>     /*0x11c */ float unk_11c;
> };
> ```

add an empty line below
___
*[`src/Game/AirOctaDataMgrTemp.cpp` line 4 at r1](https://reviewable.io/reviews/zeldaret/botw/121#-NZrc5GmE5eaU7yXwmMk:-NZrc5GmE5eaU7yXwmMl:brkw56k) ([raw file](https://github.com/zeldaret/botw/blob/2bb7c1ee40a060cc487de0475bc81eec2d6fc247/src/Game/AirOctaDataMgrTemp.cpp#L4)):*
> ```cpp
> namespace uking {
> 
> void AirOctaDataMgr::sub_71002fb17c() {
> ```

call this something more descriptive (even if it's just a placeholder name like updateFCHeight); sub_xxxxx names should be avoided unless you really can't find anything more descriptive / have absolutely no idea what the function is doing
___
*[`src/Game/CMakeLists.txt` line 9 at r1](https://reviewable.io/reviews/zeldaret/botw/121#-NZrcIyUE4HVT-R8TDI3:-NZrcIyVEQJQCYL36bS7:b-83a3uk) ([raw file](https://github.com/zeldaret/botw/blob/2bb7c1ee40a060cc487de0475bc81eec2d6fc247/src/Game/CMakeLists.txt#L9)):*
> ```CMake
> 
> target_sources(uking PRIVATE
>   AirOctaDataMgrTemp.h
> ```

I think this probably belongs in src/Game/AI/AI/AirOcta (create any folder that doesn't exist)
___
*[`src/Game/CMakeLists.txt` line 9 at r1](https://reviewable.io/reviews/zeldaret/botw/121#-NZrdMnP5VDFf03eF5FE:-NZrdMnP5VDFf03eF5FF:bmvn9kd) ([raw file](https://github.com/zeldaret/botw/blob/2bb7c1ee40a060cc487de0475bc81eec2d6fc247/src/Game/CMakeLists.txt#L9)):*
> ```CMake
> 
> target_sources(uking PRIVATE
>   AirOctaDataMgrTemp.h
> ```

also, we probably don't want that Temp in the name
___
*[`src/Game/CMakeLists.txt` line 21 at r1](https://reviewable.io/reviews/zeldaret/botw/121#-NZrcYfn0lXZhRAE7exC:-NZrcYfn0lXZhRAE7exD:b4wldth) ([raw file](https://github.com/zeldaret/botw/blob/2bb7c1ee40a060cc487de0475bc81eec2d6fc247/src/Game/CMakeLists.txt#L21)):*
> ```CMake
>   E3Mgr.cpp
>   E3Mgr.h
> ```

revert this
___
*[`src/Game/AI/AI/aiAirOctaFlyUp.h` line 3 at r1](https://reviewable.io/reviews/zeldaret/botw/121#-NZrcm3M0H9S8dxb9i4X:-NZrcm3M0H9S8dxb9i4Y:b-y3bdvl) ([raw file](https://github.com/zeldaret/botw/blob/2bb7c1ee40a060cc487de0475bc81eec2d6fc247/src/Game/AI/AI/aiAirOctaFlyUp.h#L3)):*
> ```objc
> #pragma once
> 
> #include "Game/AI/AI/aiAirOctaRoot.h"
> ```

move this include to the .cpp - you're not using anything from AirOctaRoot in the header itself
___
*[`src/Game/AI/AI/aiAirOctaFlyUp.h` line 4 at r1](https://reviewable.io/reviews/zeldaret/botw/121#-NZrccSr77i-reMBJqjd:-NZrccSr77i-reMBJqje:b-pv8t7z) ([raw file](https://github.com/zeldaret/botw/blob/2bb7c1ee40a060cc487de0475bc81eec2d6fc247/src/Game/AI/AI/aiAirOctaFlyUp.h#L4)):*
> ```objc
> 
> #include "Game/AI/AI/aiAirOctaRoot.h"
> #include "Game/AirOctaDataMgrTemp.h"
> ```

move this include to the .cpp - you don't need it as a forward declaration will suffice here.
___
*[`src/Game/AI/AI/aiAirOctaFlyUp.h` line 5 at r1](https://reviewable.io/reviews/zeldaret/botw/121#-NZrcyRE6b7gjKHvZPCc:-NZrcyRF3_fG9_qbqrMO:b-n84gh3) ([raw file](https://github.com/zeldaret/botw/blob/2bb7c1ee40a060cc487de0475bc81eec2d6fc247/src/Game/AI/AI/aiAirOctaFlyUp.h#L5)):*
> ```objc
> #include "Game/AI/AI/aiAirOctaRoot.h"
> #include "Game/AirOctaDataMgrTemp.h"
> #include "KingSystem/ActorSystem/actActor.h"
> ```

move this include to the .cpp
___
*[`src/Game/AI/AI/aiAirOctaFlyUp.h` line 7 at r1](https://reviewable.io/reviews/zeldaret/botw/121#-NZrcynODhK3MK315B9b:-NZrcynODhK3MK315B9c:b-n84gh3) ([raw file](https://github.com/zeldaret/botw/blob/2bb7c1ee40a060cc487de0475bc81eec2d6fc247/src/Game/AI/AI/aiAirOctaFlyUp.h#L7)):*
> ```objc
> #include "KingSystem/ActorSystem/actActor.h"
> #include "KingSystem/ActorSystem/actAiAi.h"
> #include "KingSystem/ActorSystem/actBaseProcLink.h"
> ```

move this include to the .cpp
___
*[`src/Game/AI/AI/aiAirOctaFlyUp.h` line 8 at r1](https://reviewable.io/reviews/zeldaret/botw/121#-NZrd9xa3iCpHmzMFwDb:-NZrd9xa3iCpHmzMFwDc:b-hynfim) ([raw file](https://github.com/zeldaret/botw/blob/fd527f92164b8efdb746cffcf23c4f033fbffa76/src/Game/AI/AI/aiAirOctaFlyUp.h#L8)):*
> ```objc
> 
> class AirOctaFlyUp : public ksys::act::ai::Ai {
>     SEAD_RTTI_OVERRIDE(AirOctaFlyUp, ksys::act::ai::Ai)
> ```

revert this; this should not have been removed
___
*[`src/Game/AI/AI/aiAirOctaFlyUp.h` line 11 at r1](https://reviewable.io/reviews/zeldaret/botw/121#-NZrcgEs4T7gKzi8TB1P:-NZrcgEs4T7gKzi8TB1Q:b-fh4nop) ([raw file](https://github.com/zeldaret/botw/blob/2bb7c1ee40a060cc487de0475bc81eec2d6fc247/src/Game/AI/AI/aiAirOctaFlyUp.h#L11)):*
> ```objc
> 
> class AirOctaFlyUp : public ksys::act::ai::Ai {
>     friend uking::AirOctaDataMgr;
> ```

`friend class AirOctaDataMgr;`
___
*[`src/Game/AI/AI/aiAirOctaFlyUp.h` line 25 at r1](https://reviewable.io/reviews/zeldaret/botw/121#-NZrd--k-iZ_xRum1llb:-NZrd--k-iZ_xRum1llc:bbkspnk) ([raw file](https://github.com/zeldaret/botw/blob/2bb7c1ee40a060cc487de0475bc81eec2d6fc247/src/Game/AI/AI/aiAirOctaFlyUp.h#L25)):*
> ```objc
> 
> protected:
>     uking::AirOctaDataMgr* getDataMgr() {
> ```

this can be a const member function as it doesn't modify the instance. `AIrOctaDataMgr* getDataMgr() const { ... }`

(also you don't need the uking:: because you are already in the uking:: namespace)
___
*[`src/Game/AI/AI/aiAirOctaFlyUp.cpp` line 3 at r1](https://reviewable.io/reviews/zeldaret/botw/121#-NZrdPb_9Ghco-1k1FT_:-NZrdPb_9Ghco-1k1FTa:b4nnv4t) ([raw file](https://github.com/zeldaret/botw/blob/2bb7c1ee40a060cc487de0475bc81eec2d6fc247/src/Game/AI/AI/aiAirOctaFlyUp.cpp#L3)):*
> ```cpp
> #include "Game/AI/AI/aiAirOctaFlyUp.h"
> #include "Game/AirOctaDataMgrTemp.h"
> #include "Game/DLC/aocHardModeManager.h"
> ```

seems unused?
___
*[`src/Game/AI/AI/aiAirOctaFlyU [...]

2023-07-09 23:24 UTC, bomba1749 reviewed
> *[Reviewable](https://reviewable.io/reviews/zeldaret/botw/121)* status: 12 of 13 files reviewed, 38 unresolved discussions (waiting on @leoetlino)

___
*[`src/Game/AirOctaDataMgrTemp.h` line 2 at r1](https://reviewable.io/reviews/zeldaret/botw/121#-NZrb79k7qiCKhSr_k-T:-NZwqW7HBNajKOTmWdde:b-896fix) ([raw file](https://github.com/zeldaret/botw/blob/2bb7c1ee40a060cc487de0475bc81eec2d6fc247/src/Game/AirOctaDataMgrTemp.h#L2)):*
<details><summary><i>Previously, leoetlino (Léo Lam) wrote…</i></summary><blockquote>

please add empty lines (one after the pragma and another after the include)
</blockquote></details>

Done.
___
*[`src/Game/AirOctaDataMgrTemp.h` line 3 at r1](https://reviewable.io/reviews/zeldaret/botw/121#-NZrbDOy5vU-N38hCv1z:-NZwqWma7Yc_xfYMvyNc:b-896fix) ([raw file](https://github.com/zeldaret/botw/blob/2bb7c1ee40a060cc487de0475bc81eec2d6fc247/src/Game/AirOctaDataMgrTemp.h#L3)):*
<details><summary><i>Previously, leoetlino (Léo Lam) wrote…</i></summary><blockquote>

add an empty line below
</blockquote></details>

Done.
___
*[`src/Game/AirOctaDataMgrTemp.h` line 5 at r1](https://reviewable.io/reviews/zeldaret/botw/121#-NZrbI_w7jLzTcuAwqKO:-NZwqZCvBYYjv6wuiKQz:b-896fix) ([raw file](https://github.com/zeldaret/botw/blob/2bb7c1ee40a060cc487de0475bc81eec2d6fc247/src/Game/AirOctaDataMgrTemp.h#L5)):*
<details><summary><i>Previously, leoetlino (Léo Lam) wrote…</i></summary><blockquote>

add `#include <prim/seadRuntimeTypeInfo.h>` (you should include what you use and avoid indirect includes)
</blockquote></details>

Done.
___
*[`src/Game/AirOctaDataMgrTemp.h` line 6 at r1](https://reviewable.io/reviews/zeldaret/botw/121#-NZrbxTAEriANv2M8p3s:-NZwqZtTB4YjnGx0FlTN:b-896fix) ([raw file](https://github.com/zeldaret/botw/blob/2bb7c1ee40a060cc487de0475bc81eec2d6fc247/src/Game/AirOctaDataMgrTemp.h#L6)):*
<details><summary><i>Previously, leoetlino (Léo Lam) wrote…</i></summary><blockquote>

I'd recommend using this type definition as it's more complete compared to yours: https://discord.com/channels/688807550715560050/745633101157498880/1124088376123994142
</blockquote></details>

Done.
___
*[`src/Game/AirOctaDataMgrTemp.h` line 21 at r1](https://reviewable.io/reviews/zeldaret/botw/121#-NZrbF1REyu1pFOJt22j:-NZwqXClDuGpCw5I-d35:b-896fix) ([raw file](https://github.com/zeldaret/botw/blob/2bb7c1ee40a060cc487de0475bc81eec2d6fc247/src/Game/AirOctaDataMgrTemp.h#L21)):*
<details><summary><i>Previously, leoetlino (Léo Lam) wrote…</i></summary><blockquote>

add an empty line below
</blockquote></details>

Done.
___
*[`src/Game/AirOctaDataMgrTemp.cpp` line 4 at r1](https://reviewable.io/reviews/zeldaret/botw/121#-NZrc5GmE5eaU7yXwmMk:-NZwq_my5q8pYw_uGLKZ:b-896fix) ([raw file](https://github.com/zeldaret/botw/blob/2bb7c1ee40a060cc487de0475bc81eec2d6fc247/src/Game/AirOctaDataMgrTemp.cpp#L4)):*
<details><summary><i>Previously, leoetlino (Léo Lam) wrote…</i></summary><blockquote>

call this something more descriptive (even if it's just a placeholder name like updateFCHeight); sub_xxxxx names should be avoided unless you really can't find anything more descriptive / have absolutely no idea what the function is doing
</blockquote></details>

Done.
___
*[`src/Game/CMakeLists.txt` line 9 at r1](https://reviewable.io/reviews/zeldaret/botw/121#-NZrcIyUE4HVT-R8TDI3:-NZwqgAd4Ov-ZHMMmiPb:b-896fix) ([raw file](https://github.com/zeldaret/botw/blob/2bb7c1ee40a060cc487de0475bc81eec2d6fc247/src/Game/CMakeLists.txt#L9)):*
<details><summary><i>Previously, leoetlino (Léo Lam) wrote…</i></summary><blockquote>

I think this probably belongs in src/Game/AI/AI/AirOcta (create any folder that doesn't exist)
</blockquote></details>

Done.
___
*[`src/Game/CMakeLists.txt` line 9 at r1](https://reviewable.io/reviews/zeldaret/botw/121#-NZrdMnP5VDFf03eF5FE:-NZwqheS0jgRpCc7j-ii:b-896fix) ([raw file](https://github.com/zeldaret/botw/blob/2bb7c1ee40a060cc487de0475bc81eec2d6fc247/src/Game/CMakeLists.txt#L9)):*
<details><summary><i>Previously, leoetlino (Léo Lam) wrote…</i></summary><blockquote>

also, we probably don't want that Temp in the name
</blockquote></details>

Done.
___
*[`src/Game/CMakeLists.txt` line 21 at r1](https://reviewable.io/reviews/zeldaret/botw/121#-NZrcYfn0lXZhRAE7exC:-NZwqiYX3iMRsY-KI2qI:b-896fix) ([raw file](https://github.com/zeldaret/botw/blob/2bb7c1ee40a060cc487de0475bc81eec2d6fc247/src/Game/CMakeLists.txt#L21)):*
<details><summary><i>Previously, leoetlino (Léo Lam) wrote…</i></summary><blockquote>

revert this
</blockquote></details>

Done.
___
*[`src/Game/AI/AI/aiAirOctaFlyUp.h` line 3 at r1](https://reviewable.io/reviews/zeldaret/botw/121#-NZrcm3M0H9S8dxb9i4X:-NZwqkGMDBNV5HsJDpyn:b-896fix) ([raw file](https://github.com/zeldaret/botw/blob/2bb7c1ee40a060cc487de0475bc81eec2d6fc247/src/Game/AI/AI/aiAirOctaFlyUp.h#L3)):*
<details><summary><i>Previously, leoetlino (Léo Lam) wrote…</i></summary><blockquote>

move this include to the .cpp - you're not using anything from AirOctaRoot in the header itself
</blockquote></details>

Done.
___
*[`src/Game/AI/AI/aiAirOctaFlyUp.h` line 4 at r1](https://reviewable.io/reviews/zeldaret/botw/121#-NZrccSr77i-reMBJqjd:-NZwr9lbErDdM3v-Xilv:b-896fix) ([raw file](https://github.com/zeldaret/botw/blob/2bb7c1ee40a060cc487de0475bc81eec2d6fc247/src/Game/AI/AI/aiAirOctaFlyUp.h#L4)):*
<details><summary><i>Previously, leoetlino (Léo Lam) wrote…</i></summary><blockquote>

move this include to the .cpp - you don't need it as a forward declaration will suffice here.
</blockquote></details>

Done.
___
*[`src/Game/AI/AI/aiAirOctaFlyUp.h` line 5 at r1](https://reviewable.io/reviews/zeldaret/botw/121#-NZrcyRE6b7gjKHvZPCc:-NZwrIP7DRAgVaQ7jwE3:b-896fix) ([raw file](https://github.com/zeldaret/botw/blob/2bb7c1ee40a060cc487de0475bc81eec2d6fc247/src/Game/AI/AI/aiAirOctaFlyUp.h#L5)):*
<details><summary><i>Previously, leoetlino (Léo Lam) wrote…</i></summary><blockquote>

move this include to the .cpp
</blockquote></details>

Done.
___
*[`src/Game/AI/AI/aiAirOctaFlyUp.h` line 7 at r1](https://reviewable.io/reviews/zeldaret/botw/121#-NZrcynODhK3MK315B9b:-NZwrJPzC0rDk3LQWisU:bj477hk) ([raw file](https://github.com/zeldaret/botw/blob/2bb7c1ee40a060cc487de0475bc81eec2d6fc247/src/Game/AI/AI/aiAirOctaFlyUp.h#L7)):*
<details><summary><i>Previously, leoetlino (Léo Lam) wrote…</i></summary><blockquote>

move this include to the .cpp
</blockquote></details>

I can't get this to work, also would they have really coded it this way?
___
*[`src/Game/AI/AI/aiAirOctaFlyUp.h` line 8 at r1](https://reviewable.io/reviews/zeldaret/botw/121#-NZrd9xa3iCpHmzMFwDb:-NZwrQsR9tM5QWZ6SlHQ:b-896fix) ([raw file](https://github.com/zeldaret/botw/blob/fd527f92164b8efdb746cffcf23c4f033fbffa76/src/Game/AI/AI/aiAirOctaFlyUp.h#L8)):*
<details><summary><i>Previously, leoetlino (Léo Lam) wrote…</i></summary><blockquote>

revert this; this should not have been removed
</blockquote></details>

Done.
___
*[`src/Game/AI/AI/aiAirOctaFlyUp.h` line 25 at r1](https://reviewable.io/reviews/zeldaret/botw/121#-NZrd--k-iZ_xRum1llb:-NZwrS162icUPNK0nJSo:b-896fix) ([raw file](https://github.com/zeldaret/botw/blob/2bb7c1ee40a060cc487de0475bc81eec2d6fc247/src/Game/AI/AI/aiAirOctaFlyUp.h#L25)):*
<details><summary><i>Previously, leoetlino (Léo Lam) wrote…</i></summary><blockquote>

this can be a const member function as it doesn't modify the instance. `AIrOctaDataMgr* getDataMgr() const { ... }`

(also you don't need the uking:: because you are already in the uking:: namespace)
</blockquote></details>

Done.
___
*[`src/Game/AI/AI/aiAirOctaFlyUp.cpp` line 3 at r1](https://reviewable.io/reviews/zeldaret/botw/121#-NZrdPb_9Ghco-1k1FT_:-NZwrUr00NKlJ5M6zbTB:b-896fix) ([raw file](https://github.com/zeldaret/botw/blob/2bb7c1ee40a060cc487de0475bc81eec2d6fc247/src/Game/AI/AI/aiAirOctaFlyUp.cpp#L3)):*
<details><summary><i>Previously, leoetlino (Léo Lam) wrote…</i></summary><blockquote>

seems unused?
</blockquote></details>

Done.
___
*[`src/Game/AI/AI/aiAirOctaFlyUp.cpp` line 6 at r1](https://reviewable.io/reviews/zeldaret/botw/121 [...]

2023-07-09 23:51 UTC, bomba1749 commented
ok, ive fixed all the issues that i understand how to. There's also some changes that arent related to airoctaflyup, because ive also been working on airoctareaction and that relys on functions in some of the same files as airoctaflyup.

2023-07-10 02:43 UTC, bomba1749 reviewed
> *[Reviewable](https://reviewable.io/reviews/zeldaret/botw/121)* status: 1 of 16 files reviewed, 38 unresolved discussions (waiting on @leoetlino)

___
*[`src/KingSystem/ActorSystem/actActorLinkConstDataAccess.h` line 40 at r1](https://reviewable.io/reviews/zeldaret/botw/121#-NZrhnxDBJf4za8T2xvZ:-NZxfQCK4UnS38MCvVSQ:bmtqrje) ([raw file](https://github.com/zeldaret/botw/blob/2bb7c1ee40a060cc487de0475bc81eec2d6fc247/src/KingSystem/ActorSystem/actActorLinkConstDataAccess.h#L40)):*
<details><summary><i>Previously, bomba1749 wrote…</i></summary><blockquote>

getMessageTransceiverId is always called as a void so it wont let me return anything
</blockquote></details>

ok, i figured out how to make it a const but i cant figure out how to make it return something.


<!-- Sent from Reviewable.io -->

2023-07-11 01:24 UTC, bomba1749 reviewed
> *[Reviewable](https://reviewable.io/reviews/zeldaret/botw/121)* status: 1 of 16 files reviewed, 38 unresolved discussions (waiting on @leoetlino)

___
*[`src/KingSystem/ActorSystem/AS/ASList.h` line 5 at r1](https://reviewable.io/reviews/zeldaret/botw/121#-NZri41A-WNXvbANlhYQ:-N_1Y-z1B0xXAeC5SdLf:b-896fix) ([raw file](https://github.com/zeldaret/botw/blob/2bb7c1ee40a060cc487de0475bc81eec2d6fc247/src/KingSystem/ActorSystem/AS/ASList.h#L5)):*
<details><summary><i>Previously, leoetlino (Léo Lam) wrote…</i></summary><blockquote>

rename + give those parameters better names if you can (a4 is clearly "name" for instance)
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-07-11 01:42 UTC, bomba1749 reviewed
> *[Reviewable](https://reviewable.io/reviews/zeldaret/botw/121)* status: 1 of 16 files reviewed, 38 unresolved discussions (waiting on @leoetlino)

___
*[`src/Game/AI/AI/aiAirOctaFlyUp.h` line 7 at r1](https://reviewable.io/reviews/zeldaret/botw/121#-NZrcynODhK3MK315B9b:-N_1bIrACUgU0i_OSaG9:b-896fix) ([raw file](https://github.com/zeldaret/botw/blob/2bb7c1ee40a060cc487de0475bc81eec2d6fc247/src/Game/AI/AI/aiAirOctaFlyUp.h#L7)):*
<details><summary><i>Previously, bomba1749 wrote…</i></summary><blockquote>

I can't get this to work, also would they have really coded it this way?
</blockquote></details>

Done.
___
*[`src/Game/AI/AI/aiAirOctaFlyUp.h` line 11 at r1](https://reviewable.io/reviews/zeldaret/botw/121#-NZrcgEs4T7gKzi8TB1P:-N_1bK340Biej5CVRL3e:b-896fix) ([raw file](https://github.com/zeldaret/botw/blob/2bb7c1ee40a060cc487de0475bc81eec2d6fc247/src/Game/AI/AI/aiAirOctaFlyUp.h#L11)):*
<details><summary><i>Previously, leoetlino (Léo Lam) wrote…</i></summary><blockquote>

`friend class AirOctaDataMgr;`
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-09-10 18:25 UTC, leoetlino requested changes
please make sure to re-run clang-format. there are formatting issues in several files

> Reviewed 1 of 1 files at r3, 1 of 1 files at r4, 1 of 1 files at r5, 1 of 3 files at r6, 2 of 2 files at r8, 1 of 1 files at r10, 3 of 4 files at r11, 1 of 1 files at r19, 1 of 1 files at r20, 2 of 2 files at r23, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/zeldaret/botw/121#-:-Ne-K_fd4UfyYk2koUFn:b-sykb4s)* status: 15 of 16 files reviewed, 12 unresolved discussions (waiting on @bomba1749)

___
*[`src/Game/AI/AI/aiAirOctaFlyUp.h` line 3 at r23](https://reviewable.io/reviews/zeldaret/botw/121#-Ne-Jq0E5vhkRu4yK3hE:-Ne-Jq0E5vhkRu4yK3hF:b8ofx68) ([raw file](https://github.com/zeldaret/botw/blob/665357f944b61ba71d44237b0dac2e5749a12178/src/Game/AI/AI/aiAirOctaFlyUp.h#L3)):*
> ```objc
> #pragma once
> 
> #include "Game/AI/AI/AirOcta/AirOctaDataMgr.h"
> ```

I think you meant to move the AirOctaDataMgr.h include to the .cpp instead of leaving it here

the actAiAi.h include should be added back as that is the one we actually need for AirOctaFlyUp
___
*[`src/Game/AI/AI/aiAirOctaFlyUp.cpp` line 26 at r23](https://reviewable.io/reviews/zeldaret/botw/121#-Ne-K6444RUnKYZdW6CB:-Ne-K6444RUnKYZdW6CC:bievlvx) ([raw file](https://github.com/zeldaret/botw/blob/665357f944b61ba71d44237b0dac2e5749a12178/src/Game/AI/AI/aiAirOctaFlyUp.cpp#L26)):*
> ```cpp
>     return;
>     }
>     auto deltaTime = ksys::VFR::instance()->getDeltaTime();
> ```

something like dt works well enough (as a rule of thumb, shorter/more common variable names are easier to read than longer names, even if more descriptive. obviously single letter names are not always a good idea, but "dt" is an established shorthand for "delta time")
___
*[`src/Game/AI/AI/aiAirOctaFlyUp.cpp` line 28 at r23](https://reviewable.io/reviews/zeldaret/botw/121#-Ne-GODv13vWx19QWVs3:-Ne-GODv13vWx19QWVs4:b9s3cgy) ([raw file](https://github.com/zeldaret/botw/blob/665357f944b61ba71d44237b0dac2e5749a12178/src/Game/AI/AI/aiAirOctaFlyUp.cpp#L28)):*
> ```cpp
>     auto deltaTime = ksys::VFR::instance()->getDeltaTime();
>     mElapsedTime += deltaTime;
>     auto smallest_time = sead::Mathf::min(1.0f, mElapsedTime / *mFlyUpDuration_s);
> ```

something like `fly_up_cycles` would make more sense. the min(1.0, ...) part isn't important
___
*[`src/Game/AI/AI/aiAirOctaFlyUp.cpp` line 30 at r23](https://reviewable.io/reviews/zeldaret/botw/121#-Ne-GZWs27p3kCiqB2E1:-Ne-GZWs27p3kCiqB2E2:bffa7nj) ([raw file](https://github.com/zeldaret/botw/blob/665357f944b61ba71d44237b0dac2e5749a12178/src/Game/AI/AI/aiAirOctaFlyUp.cpp#L30)):*
> ```cpp
>     auto smallest_time = sead::Mathf::min(1.0f, mElapsedTime / *mFlyUpDuration_s);
>     auto smallest_time2 = smallest_time * 2.f;
>     auto smallest_time3 = (smallest_time * 2.f) - 1.f;
> ```

let's avoid making too many variables if there is no point to having them, as that just hurts code readability (especially when we have placeholder names). could you try removing smallest_time3 and smallest_time5?
___
*[`src/Game/AI/AI/aiAirOctaFlyUp.cpp` line 40 at r23](https://reviewable.io/reviews/zeldaret/botw/121#-Ne-GKfR5ZX401DdibqC:-Ne-GKfR5ZX401DdibqD:bnkuy1y) ([raw file](https://github.com/zeldaret/botw/blob/665357f944b61ba71d44237b0dac2e5749a12178/src/Game/AI/AI/aiAirOctaFlyUp.cpp#L40)):*
> ```cpp
>             auto currentChild = getCurrentChild();
>             if (currentChild->isFinished() || currentChild->isFailed()) {
>                 auto ASList = getActor()->getASList();
> ```

as_list
___
*[`src/Game/AI/AI/aiAirOctaFlyUp.cpp` line 79 at r23](https://reviewable.io/reviews/zeldaret/botw/121#-Ne-H6dDAjfNDNeg3_1f:-Ne-H6dDAjfNDNeg3_1g:b-cqjxid) ([raw file](https://github.com/zeldaret/botw/blob/665357f944b61ba71d44237b0dac2e5749a12178/src/Game/AI/AI/aiAirOctaFlyUp.cpp#L79)):*
> ```cpp
>     }
>         if (*user_data == 3) {
>             Ai::changeChild("終了");  // END IN JAPANESE
> ```

`// "Ended"`
___
*[`src/Game/AI/AI/AirOcta/AirOctaDataMgr.h` line 13 at r23](https://reviewable.io/reviews/zeldaret/botw/121#-Ne-HGNH2QuBkpBd90-S:-Ne-HGNH2QuBkpBd90-T:bhiuapv) ([raw file](https://github.com/zeldaret/botw/blob/665357f944b61ba71d44237b0dac2e5749a12178/src/Game/AI/AI/AirOcta/AirOctaDataMgr.h#L13)):*
> ```objc
> public:
>     ksys::act::BaseProcLink& getProc() { return mBaseProcLink; }
>     void ChangeOctasYheightMaybe();
> ```

change...  (see https://botw.link/contribute/coding-guidelines)
___
*[`src/KingSystem/ActorSystem/actActor.h` line 21 at r23](https://reviewable.io/reviews/zeldaret/botw/121#-Ne-HRW4AvlQgIrfi_0-:-Ne-HRW4AvlQgIrfi_00:b-6ssji1) ([raw file](https://github.com/zeldaret/botw/blob/665357f944b61ba71d44237b0dac2e5749a12178/src/KingSystem/ActorSystem/actActor.h#L21)):*
> ```objc
> #include "KingSystem/Utils/AtomicLongBitFlag.h"
> #include "KingSystem/Utils/Thread/ActorMessageTransceiver.h"
> #include "Game/Damage/dmgDamageManagerBase.h"
> ```

please forward declare the damage manager thing as well - we really want to avoid unnecessary includes as that'll slow down builds a lot

(also, as a rule of thumb, we shouldn't be including a Game/ header in KingSystem/ because Game is built upon KingSystem and not the other way round - I wonder if that means DamageManager should actually be in KingSystem rather than in Game... not something to fix in this PR anyway.)
___
*[`src/KingSystem/ActorSystem/actActorLinkConstDataAccess.h` line 40 at r1](https://reviewable.io/reviews/zeldaret/botw/121#-NZrhnxDBJf4za8T2xvZ:-Ne-IT5J7HWkO9TuT-mc:bhvageq) ([raw file](https://github.com/zeldaret/botw/blob/2bb7c1ee40a060cc487de0475bc81eec2d6fc247/src/KingSystem/ActorSystem/actActorLinkConstDataAccess.h#L40)):*
<details><summary><i>Previously, bomba1749 wrote…</i></summary><blockquote>

ok, i figured out how to make it a const but i cant figure out how to make it return something.
</blockquote></details>

does this work? `const MesTransceiverId& getMessageTransceiverId() const;` 
___
*[`src/KingSystem/ActorSystem/AS/ASList.h` line 6 at r23](https://reviewable.io/reviews/zeldaret/botw/121#-Ne-IdVkAbvxKFFlho_C:-Ne-IdVkAbvxKFFlho_D:btg2ujl) ([raw file](https://github.com/zeldaret/botw/blob/665357f944b61ba71d44237b0dac2e5749a12178/src/KingSystem/ActorSystem/AS/ASList.h#L6)):*
> ```objc
> class ASList{
> public:
> void StartAnimationMaybe( f32 a2, f32 a3, const sead::SafeString& animation_ASDefine, int buffer_size, int string_length, bool a7);
> ```

startAnimationMaybe
___
*[`src/KingSystem/ActorSystem/AS/ASList.h` line 6 at r23](https://reviewable.io/reviews/zeldaret/botw/121#-Ne-Ii9zER6Fwe_JPyBX:-Ne-Ii9zER6Fwe_JPyBY:b-ngkz52) ([raw file](https://github.com/zeldaret/botw/blob/665357f944b61ba71d44237b0dac2e5749a12178/src/KingSystem/ActorSystem/AS/ASList.h#L6)):*
> ```objc
> class ASList{
> public:
> void StartAnimationMaybe( f32 a2, f32 a3, const sead::SafeString& animation_ASDefine, int buffer_size, int string_length, bool a7);
> ```

suggestions:

* animation_ASDefine -> animation
* buffer_size -> give this a placeholder if you don't know what this is -- "buffer_size" makes things too confusing (what buffer?)
* ditto for string_length (what string are you referring to? basically, imagine you're looking at this ASList.h file for the first time and trying to start an animation by calling this function. you should try to ensure that the parameter names make sense)
___
*[`src/KingSystem/ActorSystem/AS/ASList.h` line 7 at r23](https://reviewable.io/reviews/zeldaret/botw/121#-Ne-JHKZ8hgsdvFhWgrJ:-Ne-JHKZ8hgsdvFhWgrK:b17orux) ([raw file](https://github.com/zeldaret/botw/blob/665357f944b61ba71d44237b0dac2e5749a12178/src/KingSystem/ActorSystem/AS/ASList.h#L7)):*
> ```objc
> public:
> void StartAnimationMaybe( f32 a2, f32 a3, const sead::SafeString& animation_ASDefine, int buffer_size, int string_length, bool a7);
> bool GoLimpFromHeadShotMaybe(u32 a1, const sead::SafeString& SafeString, u32 a2) ;
> ```

likewise SafeString is an inappropriate name for the parameter


<!-- Sent from Reviewable.io -->

2023-09-12 00:24 UTC, bomba1749 commented
i cant do the one for moving the airoctadatamgr include to the cpp because it needs to be there for the airoctadatamgr** data_mgr class variable and i cant do the one about removing the damagemgr include because then it cant call any of its functions, but besides those I think everything's done.

2023-10-11 19:12 UTC, leoetlino commented
So sorry for the delay - I'll take a look at the latest changes this weekend (and hopefully this can be merged then)

2023-10-15 21:02 UTC, leoetlino requested changes
> Reviewed 1 of 1 files at r24, 2 of 2 files at r26, 1 of 1 files at r27, 1 of 1 files at r28, 1 of 2 files at r29, 1 of 1 files at r31, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/zeldaret/botw/121)* status: 17 of 18 files reviewed, 4 unresolved discussions (waiting on @bomba1749)

___
*[`src/Game/AI/AI/aiAirOctaFlyUp.cpp` line 29 at r31](https://reviewable.io/reviews/zeldaret/botw/121#-Ngp6-PkEYRbr55cvGeI:-Ngp6-Pl83zHoItR2vKT:b-a29o03) ([raw file](https://github.com/zeldaret/botw/blob/b66c16f84c520a4e30a3dd84de468e28b6eb7372/src/Game/AI/AI/aiAirOctaFlyUp.cpp#L29)):*
> ```cpp
>     auto dt = ksys::VFR::instance()->getDeltaTime();
>     mElapsedTime += dt;
>     auto min = (sead::Mathf::min(1.0f, mElapsedTime / *mFlyUpDuration_s) * 2.f) - 1.f;
> ```

sorry, just to clarify my previous comments:

* `min(1.0f, mElapsedTime / *mFlyUpDuration_s)` is what should be called `fly_up_cycles` because it's a duration divided by the duration of one fly up cycle - that gives you the number of cycles that have occurred in the elapsed time period. the min(1.0f, ...) part is just to ensure that you have at least one cycle
* `2.0f * fly_up_cycles - 1.0f` (what you are calling `min`) should probably be renamed, but I don't have a good suggestion. maybe `adj_fly_up_cycles` or something since it's just the number of fly up cycles but adjusted
* what you are calling `fly_up_cycles` in the current diff should be renamed to something like `fly_up_multiplier` because it acts as a multiplier for the target distance, and it's no longer a number of cycles since it's the result of an exponential
* it looks like literally every usage of what you're calling `fly_up_cycles` is followed by a multiplication by 0.5f, so consider moving that into the definition of the multiplier variable
___
*[`src/KingSystem/ActorSystem/actActor.h` line 21 at r23](https://reviewable.io/reviews/zeldaret/botw/121#-Ne-HRW4AvlQgIrfi_0-:-Ngp7vYe6mkWdJTVwZ-e:bdpd80m) ([raw file](https://github.com/zeldaret/botw/blob/665357f944b61ba71d44237b0dac2e5749a12178/src/KingSystem/ActorSystem/actActor.h#L21)):*
<details><summary><i>Previously, leoetlino (Léo Lam) wrote…</i></summary><blockquote>

please forward declare the damage manager thing as well - we really want to avoid unnecessary includes as that'll slow down builds a lot

(also, as a rule of thumb, we shouldn't be including a Game/ header in KingSystem/ because Game is built upon KingSystem and not the other way round - I wonder if that means DamageManager should actually be in KingSystem rather than in Game... not something to fix in this PR anyway.)
</blockquote></details>

this comment still applies
___
*[`src/KingSystem/ActorSystem/actActor.h` line 293 at r31](https://reviewable.io/reviews/zeldaret/botw/121#-Ngp8-9c3FF32NRp1ZHc:-Ngp8-9c3FF32NRp1ZHd:b5i059r) ([raw file](https://github.com/zeldaret/botw/blob/b66c16f84c520a4e30a3dd84de468e28b6eb7372/src/KingSystem/ActorSystem/actActor.h#L293)):*
> ```objc
>     sead::Atomic<bool>& get68f() { return _68f; }
>     float get6f0() const { return _6f0; }
>     uking::dmg::DamageManagerBase* getDamageMgrDerived();
> ```

well, which is it? does this return the base class or the derived class? (you should either fix the return type or rename the function - right now it's sending mixed signals)


<!-- Sent from Reviewable.io -->

2023-10-18 23:47 UTC, bomba1749 commented
ok the naming issues should be all fixed, i got damagemgrbase forward declared and just removed getdamagemgrderived because getDamageMgr does the exact same thing and it isnt actually being used in airoctaflyup

2023-10-21 21:13 UTC, leoetlino reviewed
you sure you got rid of getDamageMgrDerived? I still see it in the diff (also, there are 2 other unresolved comments)

> Reviewed 1 of 1 files at r32, 1 of 1 files at r33, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/zeldaret/botw/121#-:-NhJ3k8kAncgGr17XzOo:b-sthkmk)* status: 17 of 18 files reviewed, 2 unresolved discussions (waiting on @bomba1749)



<!-- Sent from Reviewable.io -->

2023-10-22 20:33 UTC, bomba1749 commented
ok i actually uploaded actactor.h this time :P. I got all of the other comments done, but ive not made fly_up_cycles being *.5 in the multiplier variable bc that leads to it diffing a lot more. Also, ive chosen to name min fly_up_turning_pts- if its a physical cycle like a sine wave it's going to have (2x the number of cycles -1) of peaks and troughs.

2024-03-09 19:54 UTC, leoetlino reviewed
Sorry for the delay in re-reviewing this. This mostly looks good to me now, but there are still 3 unresolved comments and some formatting issues (you can automatically fix them by running clang-format on the files you've edited)

> Reviewed 1 of 1 files at r30, 1 of 1 files at r34, 1 of 1 files at r36, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/zeldaret/botw/121#-:-NsZlhE63DONBRi_ZsjN:bfulo5v)* status: all files reviewed, 3 unresolved discussions (waiting on @bomba1749)

___
*[`data/uking_functions.csv` line 0 at r36](https://reviewable.io/reviews/zeldaret/botw/121#-NsZlUDhCRb0XKCH8duM:-NsZlUDhCRb0XKCH8duN:b-e90m4y) ([raw file](https://github.com/zeldaret/botw/blob/2f16a2caa4ac4bde3d557783d30d131920e844ce/data/uking_functions.csv#L0)):*
Seems like there are two WIP functions - could you update their status to either matching or non-matching?


<!-- Sent from Reviewable.io -->

2024-03-13 21:15 UTC, leoetlino approved these changes
> Reviewed 1 of 1 files at r37, 1 of 1 files at r38, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/zeldaret/botw/121)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @bomba1749)



<!-- Sent from Reviewable.io -->

2024-03-13 21:17 UTC, leoetlino commented
It seems the linter is unhappy about some of the formatting - could you run clang-format on the files it's complaining about? lgtm other than that

2024-03-13 22:32 UTC, bomba1749 commented
done!!

2024-03-18 01:44 UTC, leoetlino approved these changes
> Reviewed 1 of 1 files at r39, 1 of 1 files at r40, 1 of 1 files at r41, 1 of 1 files at r42, 1 of 1 files at r43, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/zeldaret/botw/121)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @bomba1749)



<!-- Sent from Reviewable.io -->

2024-03-18 01:44 UTC, merged