Add PlacementMap, stubs: PlacementMapMgr and PlacementMapMgrMapArray
zeldaret/botw pull request #75
Opened 2022-01-18 23:58 UTC by savage13

Added 
- PlacementMap class
- PlacementMapMgr class stub
- PlacementMapMgrMapArray class stub

Includes "OK" functions
- PlacementMap::PlacementMap
- PlacementMap::~PlacementMap

**Note:** I needed to include a `junk()` function to make sure PlacementMap ctor and dtor were included in the executable.  There is probably a more elegant method of doing this.

*Getting tired of typing Placement*

2022-01-19 00:40 UTC, notyourav commented on src/KingSystem/Map/mapPlacementMap.h
> +class PlacementMapMgrMapArray {
Could this be called `PlacementMapArray`?

2022-01-19 00:40 UTC, leoetlino requested changes
Looks quite good – thanks for starting this PlacementMap stuff! Here are a bunch of mostly stylistic comments

> Reviewed 5 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/zeldaret/botw/75#-:-Mtjj9u39w4p3iICyZPE:b-1pain3)* status: all files reviewed, 40 unresolved discussions (waiting on @savage13)

___
*[src/KingSystem/Map/CMakeLists.txt, line 25 at r1](https://reviewable.io/reviews/zeldaret/botw/75#-Mtjd5ds5HZB8rGChuzy:-Mtjd5ds5HZB8rGChuzz:bhhz3ck) ([raw file](https://github.com/zeldaret/botw/blob/d61a13e4bd4a3bafab46280f65b0364895880a54/src/KingSystem/Map/CMakeLists.txt#L25)):*
> ```CMake
>   mapStagePreActorCache.cpp
>   mapStagePreActorCache.h
>   mapPlacementMap.cpp
> ```

nitpick: the source file list should be sorted to make it easier to add new source files at the correct location and to reduce the likelihood of having git conflicts
___
*[src/KingSystem/Map/mapPlacementMap.h, line 14 at r1](https://reviewable.io/reviews/zeldaret/botw/75#-MtjeZzQ4M_kUgCVqTyu:-MtjeZzQ4M_kUgCVqTyv:bvik3ls) ([raw file](https://github.com/zeldaret/botw/blob/d61a13e4bd4a3bafab46280f65b0364895880a54/src/KingSystem/Map/mapPlacementMap.h#L14)):*
> ```objc
> namespace ksys::map {
> 
> class PlacementMapMgr; /* See Below */
> ```

The comment isn't necessary for forward declarations
___
*[src/KingSystem/Map/mapPlacementMap.h, line 19 at r1](https://reviewable.io/reviews/zeldaret/botw/75#-Mtjdr3TDBrTa7cpHeif:-Mtjdr3TDBrTa7cpHeig:bqmn1to) ([raw file](https://github.com/zeldaret/botw/blob/d61a13e4bd4a3bafab46280f65b0364895880a54/src/KingSystem/Map/mapPlacementMap.h#L19)):*
> ```objc
> class FarActorMerge;
> 
> class PlacementMapHkscRes {
> ```

I think this class is only used inside PlacementMap, so it might be more natural to declare it inside PlacementMap.

```cpp
class PlacementMap {
public:
    struct HkscRes {  // since this is just a Handle + status, a struct is fine
        enum class Status { ... };

        ... // functions

        res::Handle handle;
        Status status;
    };

    // ...
};
```
___
*[src/KingSystem/Map/mapPlacementMap.h, line 20 at r1](https://reviewable.io/reviews/zeldaret/botw/75#-MtjdNGi25fATMgnmtMI:-MtjdNGi25fATMgnmtMJ:b-3w8o2q) ([raw file](https://github.com/zeldaret/botw/blob/d61a13e4bd4a3bafab46280f65b0364895880a54/src/KingSystem/Map/mapPlacementMap.h#L20)):*
> ```objc
> 
> class PlacementMapHkscRes {
>     enum {
> ```

```cpp
enum class Status {
    _2 = 2,
    _3 = 3,
    _4 = 4,
    _5 = 5,
};
```
(IDA doesn't support enum classes / scoped enums, which is why all enums look like C enums and have redundant identifiers in the IDB)
___
*[src/KingSystem/Map/mapPlacementMap.h, line 20 at r1](https://reviewable.io/reviews/zeldaret/botw/75#-Mtjdf3Z6W_p-XUotQeC:-Mtjdf3Z6W_p-XUotQeD:b-wko1qy) ([raw file](https://github.com/zeldaret/botw/blob/d61a13e4bd4a3bafab46280f65b0364895880a54/src/KingSystem/Map/mapPlacementMap.h#L20)):*
> ```objc
> 
> class PlacementMapHkscRes {
>     enum {
> ```

This should probably be public?
___
*[src/KingSystem/Map/mapPlacementMap.h, line 33 at r1](https://reviewable.io/reviews/zeldaret/botw/75#-MtjeLdxATgt-ZUzJb2X:-MtjeLdxATgt-ZUzJb2Y:bxunmtk) ([raw file](https://github.com/zeldaret/botw/blob/d61a13e4bd4a3bafab46280f65b0364895880a54/src/KingSystem/Map/mapPlacementMap.h#L33)):*
> ```objc
>     ksys::res::Handle res;
>     s32 statusMaybe;
>     bool _54;
> ```

Do these actually exist? It seems that they are probably padding bytes.
___
*[src/KingSystem/Map/mapPlacementMap.h, line 39 at r1](https://reviewable.io/reviews/zeldaret/botw/75#-MtjeR_K9CBHfMgFTy2Z:-MtjeR_K9CBHfMgFTy2_:b-ixye4o) ([raw file](https://github.com/zeldaret/botw/blob/d61a13e4bd4a3bafab46280f65b0364895880a54/src/KingSystem/Map/mapPlacementMap.h#L39)):*
> ```objc
> 
>     void cleanup() {
>         auto r = res.getResource();
> ```

`auto*` to make it clear that `r` is a pointer
___
*[src/KingSystem/Map/mapPlacementMap.h, line 40 at r1](https://reviewable.io/reviews/zeldaret/botw/75#-MtjeoPe582ha7aykt9Z:-MtjeoPe582ha7aykt9_:b-kvad0z) ([raw file](https://github.com/zeldaret/botw/blob/d61a13e4bd4a3bafab46280f65b0364895880a54/src/KingSystem/Map/mapPlacementMap.h#L40)):*
> ```objc
>     void cleanup() {
>         auto r = res.getResource();
>         if (auto ptr = sead::DynamicCast<ksys::phys::StaticCompound>(r)) {
> ```

IMO `sc` would be a better variable name. `ptr` sounds a bit too generic and undescriptive.
___
*[src/KingSystem/Map/mapPlacementMap.h, line 47 at r1](https://reviewable.io/reviews/zeldaret/botw/75#-Mtjeco7Ar0T6ZExovHl:-Mtjeco7Ar0T6ZExovHm:b954w9y) ([raw file](https://github.com/zeldaret/botw/blob/d61a13e4bd4a3bafab46280f65b0364895880a54/src/KingSystem/Map/mapPlacementMap.h#L47)):*
> ```objc
>     }
> };
> KSYS_CHECK_SIZE_NX150(PlacementMapHkscRes, 0x58);
> ```

KingSystem/Utils/Types.h needs to be included
___
*[src/KingSystem/Map/mapPlacementMap.h, line 50 at r1](https://reviewable.io/reviews/zeldaret/botw/75#-MtjefCPDl9c0i6Ir9Wd:-MtjefCPDl9c0i6Ir9We:b-fmhptr) ([raw file](https://github.com/zeldaret/botw/blob/d61a13e4bd4a3bafab46280f65b0364895880a54/src/KingSystem/Map/mapPlacementMap.h#L50)):*
> ```objc
> 
> class PlacementMap {
>     enum { StaticMap_None = 0, StaticMap_Loaded = 1 << 0, StaticMap_Parsed = 1 << 8 };
> ```

same remark about using enum classes
___
*[src/KingSystem/Map/mapPlacementMap.h, line 53 at r1](https://reviewable.io/reviews/zeldaret/botw/75#-MtjehLzC0DxVrNUqCRe:-MtjehLzC0DxVrNUqCRf:bclwjf6) ([raw file](https://github.com/zeldaret/botw/blob/d61a13e4bd4a3bafab46280f65b0364895880a54/src/KingSystem/Map/mapPlacementMap.h#L53)):*
> ```objc
> 
> public:
>     __attribute__((noinline)) PlacementMap() {
> ```

This is probably defined in the .cpp rather than in the header. noinline shouldn't be required.
___
*[src/KingSystem/Map/mapPlacementMap.h, line 84 at r1](https://reviewable.io/reviews/zeldaret/botw/75#-Mtjf-baAQCdmZ0u4LWc:-Mtjf-baAQCdmZ0u4LWd:b-ie729f) ([raw file](https://github.com/zeldaret/botw/blob/d61a13e4bd4a3bafab46280f65b0364895880a54/src/KingSystem/Map/mapPlacementMap.h#L84)):*
> ```objc
>     }
> 
>     s32 loadStaticMap_(u8 load);
> ```

Should the u8 be a boolean?
___
*[src/KingSystem/Map/mapPlacementMap.h, line 87 at r1](https://reviewable.io/reviews/zeldaret/botw/75#-Mtjf2tf6Eu7lRF0hwtE:-Mtjf2tf6Eu7lRF0hwtF:b-jgjua5) ([raw file](https://github.com/zeldaret/botw/blob/d61a13e4bd4a3bafab46280f65b0364895880a54/src/KingSystem/Map/mapPlacementMap.h#L87)):*
> ```objc
>     void doLoadStaticMap_(bool load);
> 
>     bool parseStaticMap_(sead::ExpHeap* heap, u8* data);
> ```

sead::ExpHeap -> sead::Heap

I might have mentioned this before, but the IDB uses ExpHeap instead of Heap for historical reasons — as a rule of thumb you should always use Heap unless using a more specific heap class is *required* (in general it isn't).
___
*[src/KingSystem/Map/mapPlacementMap.h, line 88 at r1](https://reviewable.io/reviews/zeldaret/botw/75#-MtjfLwu0C_GafphoCDO:-MtjfLwu0C_GafphoCDP:bjqi2y1) ([raw file](https://github.com/zeldaret/botw/blob/d61a13e4bd4a3bafab46280f65b0364895880a54/src/KingSystem/Map/mapPlacementMap.h#L88)):*
> ```objc
> 
>     bool parseStaticMap_(sead::ExpHeap* heap, u8* data);
>     void parseMap_(sead::ExpHeap* heap, u8* data, int group, u32 idx);
> ```

Heap type
___
*[src/KingSystem/Map/mapPlacementMap.h, line 99 at r1](https://reviewable.io/reviews/zeldaret/botw/75#-MtjfRYy4coVI7Q0qsl8:-MtjfRYy4coVI7Q0qsl9:b-c0q9hd) ([raw file](https://github.com/zeldaret/botw/blob/d61a13e4bd4a3bafab46280f65b0364895880a54/src/KingSystem/Map/mapPlacementMap.h#L99)):*
> ```objc
>     s32 x_6();
>     void x_5();
>     s64 traverseStuff(sead::Vector3f vec, map::PlacementActors* pa, int a4);
> ```

Is the vector really passed by value? I wouldn't expect it to be passed by const-reference (e.g. `const sead::Vector3f&`).
___
*[src/KingSystem/Map/mapPlacementMap.h, line 99 at r1](https://reviewable.io/reviews/zeldaret/botw/75#-MtjfYpGBYqdoef5SpHO:-MtjfYpGBYqdoef5SpHP:b9cc8iw) ( [...]

2022-01-19 00:44 UTC, leoetlino reviewed
> *[Reviewable](https://reviewable.io/reviews/zeldaret/botw/75)* status: all files reviewed, 40 unresolved discussions (waiting on @notyourav and @savage13)

___
*[src/KingSystem/Map/mapPlacementMap.h, line 99 at r1](https://reviewable.io/reviews/zeldaret/botw/75#-MtjfRYy4coVI7Q0qsl8:-MtjmMGa6xtRKhDfju8U:b-js5wf6) ([raw file](https://github.com/zeldaret/botw/blob/d61a13e4bd4a3bafab46280f65b0364895880a54/src/KingSystem/Map/mapPlacementMap.h#L99)):*
<details><summary><i>Previously, leoetlino (Léo Lam) wrote…</i></summary><blockquote>

Is the vector really passed by value? I wouldn't expect it to be passed by const-reference (e.g. `const sead::Vector3f&`).
</blockquote></details>

would've expected*, sorry for the confusion :)
___
*[src/KingSystem/Map/mapPlacementMap.h, line 161 at r1](https://reviewable.io/reviews/zeldaret/botw/75#-Mtjc56WO2CExoUO0W3c-r1-161:-MtjmSBcDT5d6_r1ZKvI:b90ibx8) ([raw file](https://github.com/zeldaret/botw/blob/d61a13e4bd4a3bafab46280f65b0364895880a54/src/KingSystem/Map/mapPlacementMap.h#L161)):*
<details><summary><i>Previously, notyourav wrote…</i></summary><blockquote>

Could this be called `PlacementMapArray`?
</blockquote></details>

Yeah, I don't think putting "Mgr" in the name is necessary


<!-- Sent from Reviewable.io -->

2022-01-20 00:25 UTC, savage13 commented
I think I got everything.  

One of the `enums` needed to be u16  and the `enum class` are i32 so it conflicts with the size of the class.

Thanks for the thorough review :)

2022-01-20 00:42 UTC, leoetlino requested changes
FYI, in C++11 (and newer standards) you can specify the underlying size for an enum with `: UnderlyingType`, e.g. `enum class Foo : u16` -- there's also sead::SizedEnum if specifying the underlying type is not an option for whatever reason (codegen is usually the same but not always).

PS: there are some comments that I think may have been overlooked: make sure to check the Reviewable page to easily see what's left

> Reviewed 6 of 6 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/zeldaret/botw/75#-:-MtosCM73vdX3_k7dxVS:ba3vkex)* status: all files reviewed, 13 unresolved discussions (waiting on @notyourav and @savage13)

___
*[src/KingSystem/Map/mapPlacementMap.h, line 111 at r1](https://reviewable.io/reviews/zeldaret/botw/75#-Mtjg6aIAhJdZ0pBsiFO:-MtouBT7578kThs9v5fX:b-8pfj1t) ([raw file](https://github.com/zeldaret/botw/blob/d61a13e4bd4a3bafab46280f65b0364895880a54/src/KingSystem/Map/mapPlacementMap.h#L111)):*
<details><summary><i>Previously, leoetlino (Léo Lam) wrote…</i></summary><blockquote>

Does this function modify the vector? If `pos` is only *read*, and if it is not possible to pass a null pointer, then `pos` should be passed by const-ref.
</blockquote></details>

pos should be const, given that it's not modified.
___
*[src/KingSystem/Map/mapPlacementMap.h, line 65 at r2](https://reviewable.io/reviews/zeldaret/botw/75#-MtotABwDy5vx6KO7ojw:-MtotABwDy5vx6KO7ojx:b-bb8gk0) ([raw file](https://github.com/zeldaret/botw/blob/7d97bb6f4008ae15ab8ca6c94fb09bf03c3d307e/src/KingSystem/Map/mapPlacementMap.h#L65)):*
> ```objc
>     ~PlacementMap();
> 
>     s32 loadStaticMap_(bool load);
> ```

Generally int is preferred over s32 (in any case we should be consistent about using either int or s32 in a file)
___
*[src/KingSystem/Map/mapPlacementMap.h, line 80 at r2](https://reviewable.io/reviews/zeldaret/botw/75#-Mtot_8s5FajSuLiOMJV:-Mtot_8t1V6EM_d2oLF-:bux71uh) ([raw file](https://github.com/zeldaret/botw/blob/7d97bb6f4008ae15ab8ca6c94fb09bf03c3d307e/src/KingSystem/Map/mapPlacementMap.h#L80)):*
> ```objc
>     s32 x_6();
>     void x_5();
>     s64 traverseStuff(sead::Vector3f* vec, PlacementActors* pa, int id);
> ```

Does this really return a 64-bit integer? Nintendo almost never uses 64-bit integers. Note that Hex-Rays often gets boolean/integer return types wrong.
___
*[src/KingSystem/Map/mapPlacementMap.h, line 82 at r2](https://reviewable.io/reviews/zeldaret/botw/75#-Mtotny-COwCsBU_nSOv:-Mtotny-COwCsBU_nSOw:b-dychpm) ([raw file](https://github.com/zeldaret/botw/blob/7d97bb6f4008ae15ab8ca6c94fb09bf03c3d307e/src/KingSystem/Map/mapPlacementMap.h#L82)):*
> ```objc
>     s64 traverseStuff(sead::Vector3f* vec, PlacementActors* pa, int id);
> 
>     phys::BodyGroup* getFieldBodyGroup(u32 field_body_group_id);
> ```

id != index -- in this case the argument is an index, not a group ID.
___
*[src/KingSystem/Map/mapPlacementMap.h, line 88 at r2](https://reviewable.io/reviews/zeldaret/botw/75#-Mtou7yJAry4d7N4AIBG:-Mtou7yJAry4d7N4AIBH:b61x6w1) ([raw file](https://github.com/zeldaret/botw/blob/7d97bb6f4008ae15ab8ca6c94fb09bf03c3d307e/src/KingSystem/Map/mapPlacementMap.h#L88)):*
> ```objc
>     void x(int id, Object* obj);
>     void unloadHksc(s32 id);
>     s32 x_4(s64 id);
> ```

Is this really a s64? Nintendo almost never uses 64-bit integers.
___
*[src/KingSystem/Map/mapPlacementMapMgr.h, line 44 at r2](https://reviewable.io/reviews/zeldaret/botw/75#-Mtoub_WE4nLOSifpshT:-Mtoub_XE9H-gOy1rtOE:bi64ulk) ([raw file](https://github.com/zeldaret/botw/blob/7d97bb6f4008ae15ab8ca6c94fb09bf03c3d307e/src/KingSystem/Map/mapPlacementMapMgr.h#L44)):*
> ```objc
>     ~PlacementMapMgr() = default;
> 
>     void junk();  // Here to make compiler include MapPlacement - REMOVE
> ```

This can be removed now.
___
*[src/KingSystem/Map/mapPlacementMapMgr.h, line 46 at r2](https://reviewable.io/reviews/zeldaret/botw/75#-MtovNYQCoe6L1zfXQmT:-MtovNYQCoe6L1zfXQmU:b-boifnn) ([raw file](https://github.com/zeldaret/botw/blob/7d97bb6f4008ae15ab8ca6c94fb09bf03c3d307e/src/KingSystem/Map/mapPlacementMapMgr.h#L46)):*
> ```objc
>     void junk();  // Here to make compiler include MapPlacement - REMOVE
> 
>     s32 mNumMaps;
> ```

mNumMaps + mMaps is probably a `sead::Buffer<PlacementMap>`?
___
*[src/KingSystem/Map/mapPlacementMapMgr.h, line 58 at r2](https://reviewable.io/reviews/zeldaret/botw/75#-MtovBL33Zwicxv3UZbD:-MtovBL33Zwicxv3UZbE:bgo0hzx) ([raw file](https://github.com/zeldaret/botw/blob/7d97bb6f4008ae15ab8ca6c94fb09bf03c3d307e/src/KingSystem/Map/mapPlacementMapMgr.h#L58)):*
> ```objc
>     bool mIsShrineOrDivineBeast;
>     bool mIsShrine;
>     // char pad[6];
> ```

This comment can be removed.
___
*[src/KingSystem/Map/mapPlacementMapMgr.h, line 61 at r2](https://reviewable.io/reviews/zeldaret/botw/75#-MtounBw4ulElcVJBFP7:-MtounBw4ulElcVJBFP8:b9x3qfn) ([raw file](https://github.com/zeldaret/botw/blob/7d97bb6f4008ae15ab8ca6c94fb09bf03c3d307e/src/KingSystem/Map/mapPlacementMapMgr.h#L61)):*
> ```objc
> };
> /* Size - D0 ? */
> KSYS_CHECK_SIZE_NX150(PlacementMapMgr, 0xF0);
> ```

Yes, the size should be 0xD0. 0xF0 is incorrect. Looks like that's because PlacementMapMgr actually isn't a singleton, so the SEAD_SINGLETON stuff should be removed (and doing so will fix the size discrepancy).


<!-- Sent from Reviewable.io -->

2022-01-20 14:11 UTC, savage13 reviewed
> *[Reviewable](https://reviewable.io/reviews/zeldaret/botw/75)* status: all files reviewed, 13 unresolved discussions (waiting on @leoetlino, @notyourav, and @savage13)

___
*[src/KingSystem/Map/mapPlacementMap.h, line 50 at r1](https://reviewable.io/reviews/zeldaret/botw/75#-MtjefCPDl9c0i6Ir9Wd:-MtrmcKZAqA8FF1yos3c:b-896fix) ([raw file](https://github.com/zeldaret/botw/blob/d61a13e4bd4a3bafab46280f65b0364895880a54/src/KingSystem/Map/mapPlacementMap.h#L50)):*
<details><summary><i>Previously, leoetlino (Léo Lam) wrote…</i></summary><blockquote>

same remark about using enum classes
</blockquote></details>

Done.
___
*[src/KingSystem/Map/mapPlacementMap.h, line 99 at r1](https://reviewable.io/reviews/zeldaret/botw/75#-MtjfRYy4coVI7Q0qsl8:-MtrVc3x2yOGwxKuxY4f:b-896fix) ([raw file](https://github.com/zeldaret/botw/blob/d61a13e4bd4a3bafab46280f65b0364895880a54/src/KingSystem/Map/mapPlacementMap.h#L99)):*
<details><summary><i>Previously, leoetlino (Léo Lam) wrote…</i></summary><blockquote>

would've expected*, sorry for the confusion :)
</blockquote></details>

Done.
___
*[src/KingSystem/Map/mapPlacementMap.h, line 111 at r1](https://reviewable.io/reviews/zeldaret/botw/75#-Mtjg6aIAhJdZ0pBsiFO:-MtrX14I01qgaL9fx0aA:b-896fix) ([raw file](https://github.com/zeldaret/botw/blob/d61a13e4bd4a3bafab46280f65b0364895880a54/src/KingSystem/Map/mapPlacementMap.h#L111)):*
<details><summary><i>Previously, leoetlino (Léo Lam) wrote…</i></summary><blockquote>

pos should be const, given that it's not modified.
</blockquote></details>

Done.
___
*[src/KingSystem/Map/mapPlacementMap.h, line 115 at r1](https://reviewable.io/reviews/zeldaret/botw/75#-MtjgQHoAbWsSe6MjdpX:-MtroOFL-TKH4B7E8LrU:b-896fix) ([raw file](https://github.com/zeldaret/botw/blob/d61a13e4bd4a3bafab46280f65b0364895880a54/src/KingSystem/Map/mapPlacementMap.h#L115)):*
<details><summary><i>Previously, leoetlino (Léo Lam) wrote…</i></summary><blockquote>

Same question here: if the strings are not modified, then they should be passed by const-ref. (I'm pointing this out because most SafeStrings are passed by const-ref, so it is unusual to see SafeString pointers)
</blockquote></details>

Done.
___
*[src/KingSystem/Map/mapPlacementMap.h, line 161 at r1](https://reviewable.io/reviews/zeldaret/botw/75#-Mtjc56WO2CExoUO0W3c-r1-161:-MtrV1Gr1nxLD7lcgF57:b-896fix) ([raw file](https://github.com/zeldaret/botw/blob/d61a13e4bd4a3bafab46280f65b0364895880a54/src/KingSystem/Map/mapPlacementMap.h#L161)):*
<details><summary><i>Previously, leoetlino (Léo Lam) wrote…</i></summary><blockquote>

Yeah, I don't think putting "Mgr" in the name is necessary
</blockquote></details>

Done.
___
*[src/KingSystem/Map/mapPlacementMap.h, line 65 at r2](https://reviewable.io/reviews/zeldaret/botw/75#-MtotABwDy5vx6KO7ojw:-MtrVppXCJEaNJx9ANLk:bydz4cr) ([raw file](https://github.com/zeldaret/botw/blob/7d97bb6f4008ae15ab8ca6c94fb09bf03c3d307e/src/KingSystem/Map/mapPlacementMap.h#L65)):*
<details><summary><i>Previously, leoetlino (Léo Lam) wrote…</i></summary><blockquote>

Generally int is preferred over s32 (in any case we should be consistent about using either int or s32 in a file)
</blockquote></details>

Function prototypes now are all int, not s32.
___
*[src/KingSystem/Map/mapPlacementMap.h, line 80 at r2](https://reviewable.io/reviews/zeldaret/botw/75#-Mtot_8s5FajSuLiOMJV:-MtrVYtB56QbW65r6w2N:b-896fix) ([raw file](https://github.com/zeldaret/botw/blob/7d97bb6f4008ae15ab8ca6c94fb09bf03c3d307e/src/KingSystem/Map/mapPlacementMap.h#L80)):*
<details><summary><i>Previously, leoetlino (Léo Lam) wrote…</i></summary><blockquote>

Does this really return a 64-bit integer? Nintendo almost never uses 64-bit integers. Note that Hex-Rays often gets boolean/integer return types wrong.
</blockquote></details>

Done.
___
*[src/KingSystem/Map/mapPlacementMap.h, line 82 at r2](https://reviewable.io/reviews/zeldaret/botw/75#-Mtotny-COwCsBU_nSOv:-MtrVUNuAC3E3GgO5XfJ:b-896fix) ([raw file](https://github.com/zeldaret/botw/blob/7d97bb6f4008ae15ab8ca6c94fb09bf03c3d307e/src/KingSystem/Map/mapPlacementMap.h#L82)):*
<details><summary><i>Previously, leoetlino (Léo Lam) wrote…</i></summary><blockquote>

id != index -- in this case the argument is an index, not a group ID.
</blockquote></details>

Done.
___
*[src/KingSystem/Map/mapPlacementMap.h, line 88 at r2](https://reviewable.io/reviews/zeldaret/botw/75#-Mtou7yJAry4d7N4AIBG:-MtrVG4CAsd1Gdkaa675:b1ao6) ([raw file](https://github.com/zeldaret/botw/blob/7d97bb6f4008ae15ab8ca6c94fb09bf03c3d307e/src/KingSystem/Map/mapPlacementMap.h#L88)):*
<details><summary><i>Previously, leoetlino (Léo Lam) wrote…</i></summary><blockquote>

Is this really a s64? Nintendo almost never uses 64-bit integers.
</blockquote></details>

Removed s64 from the function prototypes.  
___
*[src/KingSystem/Map/mapPlacementMapMgr.h, line 44 at r2](https://reviewable.io/reviews/zeldaret/botw/75#-Mtoub_WE4nLOSifpshT:-MtrUoKN0iZ6-G1UfVxi:b-896fix) ([raw file](https://github.com/zeldaret/botw/blob/7d97bb6f4008ae15ab8ca6c94fb09bf03c3d307e/src/KingSystem/Map/mapPlacementMapMgr.h#L44)):*
<details><summary><i>Previously, leoetlino (Léo Lam) wrote…</i></summary><blockquote>

This can be removed now.
</blockquote></details>

Done.
___
*[src/KingSystem/Map/mapPlacementMapMgr.h, line 58 at r2](https://reviewable.io/reviews/zeldaret/botw/75#-MtovBL33Zwicxv3UZbD:-MtrUgVT1dVFxGWS7-JD:b-896fix) ([raw file](https://github.com/zeldaret/botw/blob/7d97bb6f4008ae15ab8ca6c94fb09bf03c3d307e/src/KingSystem/Map/mapPlacementMapMgr.h#L58)):*
<details><summary><i>Previously, leoetlino (Léo Lam) wrote…</i></summary><blockquote>

This comment can be removed.
</blockquote></details>

Done.
___
*[src/KingSystem/Map/mapPlacementMapMgr.h, line 61 at r2](https://reviewable.io/reviews/zeldaret/botw/75#-MtounBw4ulElcVJBFP7:-MtrUbuK8eDA6ydpfCWM:b-896fix) ([raw file](https://github.com/zeldaret/botw/blob/7d97bb6f4008ae15ab8ca6c94fb09bf03c3d307e/src/KingSystem/Map/mapPlacementMapMgr.h#L61)):*
<details><summary><i>Previously, leoetlino (Léo Lam) wrote…</i></summary><blockquote>

Yes, the size should be 0xD0. 0xF0 is incorrect. Looks like that's because PlacementMapMgr actually isn't a singleton, so the SEAD_SINGLETON stuff should be removed (and doing so will fix the size discrepancy).
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-01-20 14:15 UTC, leoetlino commented
Did you forget to push? :)

2022-01-20 14:38 UTC, savage13 reviewed
I haven't pushed yet.

> *[Reviewable](https://reviewable.io/reviews/zeldaret/botw/75#-:-MtruIMD3Bx-p8Byy_pz:b-w66cf0)* status: 3 of 7 files reviewed, 13 unresolved discussions (waiting on @leoetlino and @notyourav)

___
*[src/KingSystem/Map/mapPlacementMapMgr.h, line 46 at r2](https://reviewable.io/reviews/zeldaret/botw/75#-MtovNYQCoe6L1zfXQmT:-Mtrp_H_2scnaEqT-Yrb:b-w3flkq) ([raw file](https://github.com/zeldaret/botw/blob/7d97bb6f4008ae15ab8ca6c94fb09bf03c3d307e/src/KingSystem/Map/mapPlacementMapMgr.h#L46)):*
<details><summary><i>Previously, leoetlino (Léo Lam) wrote…</i></summary><blockquote>

mNumMaps + mMaps is probably a `sead::Buffer<PlacementMap>`?
</blockquote></details>

`sead::Buffer` is `{ s32 msize; T* mBuffer; }`.  `The PlacementMapMgr::ctor()` looks like it wants `mSize` to be at 0 offset and `mBuffer` at 8 offset.  A sead::PtrArray appears to fit the class memory layout with an additional `mSizeMax`, but the initialization of `mBuffer` in `::ctor()` does not set the `mSizeMax`.  Hmm, confused.


<!-- Sent from Reviewable.io -->

2022-01-20 14:58 UTC, leoetlino reviewed
> Reviewed 4 of 4 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/zeldaret/botw/75)* status: all files reviewed, 3 unresolved discussions (waiting on @leoetlino and @notyourav)



<!-- Sent from Reviewable.io -->

2022-01-20 15:19 UTC, savage13 reviewed
sead:Buffer works better. :smiley: 

> *[Reviewable](https://reviewable.io/reviews/zeldaret/botw/75#-:-Mts3LINCYzheZt6bKLB:b-f6j63z)* status: 6 of 7 files reviewed, 3 unresolved discussions (waiting on @leoetlino and @notyourav)



<!-- Sent from Reviewable.io -->

2022-01-20 15:26 UTC, leoetlino reviewed
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/zeldaret/botw/75)* status: all files reviewed, 3 unresolved discussions (waiting on @leoetlino, @notyourav, and @savage13)

___
*[src/KingSystem/Map/mapPlacementMapMgr.h, line 43 at r4](https://reviewable.io/reviews/zeldaret/botw/75#-Mts4B0-A317fcJBY-kG:-Mts4B0-A317fcJBY-kH:bi1n9dh) ([raw file](https://github.com/zeldaret/botw/blob/c028190362727144c62e1ea6a4d7d463c584cec3/src/KingSystem/Map/mapPlacementMapMgr.h#L43)):*
> ```objc
> 
> private:
>     sead::Buffer<PlacementMap> mMaps;
> ```

Needs an `#include <container/seadBuffer.h>`


<!-- Sent from Reviewable.io -->

2022-01-20 16:57 UTC, savage13 reviewed
> *[Reviewable](https://reviewable.io/reviews/zeldaret/botw/75)* status: all files reviewed, 3 unresolved discussions (waiting on @leoetlino and @notyourav)

___
*[src/KingSystem/Map/mapPlacementMapMgr.h, line 43 at r4](https://reviewable.io/reviews/zeldaret/botw/75#-Mts4B0-A317fcJBY-kG:-MtsPlUU49utu8xDNS3N:b-896fix) ([raw file](https://github.com/zeldaret/botw/blob/c028190362727144c62e1ea6a4d7d463c584cec3/src/KingSystem/Map/mapPlacementMapMgr.h#L43)):*
<details><summary><i>Previously, leoetlino (Léo Lam) wrote…</i></summary><blockquote>

Needs an `#include <container/seadBuffer.h>`
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-01-20 17:05 UTC, leoetlino approved these changes
lgtm, I'll let @notyourav take a look as he has worked on Placement stuff

> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/zeldaret/botw/75#-:-MtsRZP9AboxpKUiodr0:bl39m2h)* status: all files reviewed, 1 unresolved discussion (waiting on @notyourav)



<!-- Sent from Reviewable.io -->

2022-01-23 08:21 UTC, notyourav approved these changes

2022-01-23 08:33 UTC, merged