Add VideoRecorder
zeldaret/botw pull request #98
Opened 2022-07-19 19:57 UTC by ecumber

This fully decompiles the leftover VideoRecorder subsystem

2022-07-20 19:58 UTC, leoetlino requested changes
Please fix the warnings at https://ci.botw.link/#/builders/3/builds/12/steps/4/logs/stdio (you can ignore the cppcoreguidelines-pro-type-member-init warnings though)

> Reviewed 3 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/zeldaret/botw/98#-:-N7SAy8tB6oWXq0HVPnP:b5tb7lr)* status: 3 of 4 files reviewed, 7 unresolved discussions (waiting on @ecumber and @leoetlino)

___
*[`src/KingSystem/System/VideoRecorder.h` line 19 at r1](https://reviewable.io/reviews/zeldaret/botw/98#-N7S9A8S3wxK4YiUgE5h:-N7S9A8S3wxK4YiUgE5i:b-yyf6dv) ([raw file](https://github.com/zeldaret/botw/blob/954e4d28a25edd2cad0e1fc745dfae490c300dcf/src/KingSystem/System/VideoRecorder.h#L19)):*
> ```objc
>     bool isCaptureEnabled() const { return capture_enabled; }
>     int getFrameNumber() const { return frame_number; }
>     sead::FixedSafeString<0x100> getFileName() const { return filename; }
> ```

This should probably return a const reference instead of a copy. Or even `const sead::SafeString&` since it's rarely useful for external users to know the exact string buffer type.
___
*[`src/KingSystem/System/VideoRecorder.h` line 22 at r1](https://reviewable.io/reviews/zeldaret/botw/98#-N7S9W2V9aswNcxAOaKv:-N7S9W2V9aswNcxAOaKw:badjse6) ([raw file](https://github.com/zeldaret/botw/blob/954e4d28a25edd2cad0e1fc745dfae490c300dcf/src/KingSystem/System/VideoRecorder.h#L22)):*
> ```objc
> 
> private:
>     bool capture_enabled = false;  // 0x28
> ```

The offset comments are unnecessary and should be removed
___
*[`src/KingSystem/System/VideoRecorder.h` line 23 at r1](https://reviewable.io/reviews/zeldaret/botw/98#-N7S9aVb1XiyfcWmr2zW:-N7S9aVb1XiyfcWmr2zX:b-rys61m) ([raw file](https://github.com/zeldaret/botw/blob/954e4d28a25edd2cad0e1fc745dfae490c300dcf/src/KingSystem/System/VideoRecorder.h#L23)):*
> ```objc
> private:
>     bool capture_enabled = false;  // 0x28
>     bool _29 = true;       // 0x29, this gets set to true but isn't used elsewhere, no idea why
> ```

The reason why this is unused is that VideoRecorder is stubbed so the functions that would probably have used this member variable do not exist in the release builds of the game we have.
___
*[`src/KingSystem/System/VideoRecorder.h` line 31 at r1](https://reviewable.io/reviews/zeldaret/botw/98#-N7S9nTo8VtvYAB3lAMh:-N7S9nTo8VtvYAB3lAMi:b52q2ff) ([raw file](https://github.com/zeldaret/botw/blob/954e4d28a25edd2cad0e1fc745dfae490c300dcf/src/KingSystem/System/VideoRecorder.h#L31)):*
> ```objc
> }  // namespace ksys
> 
> namespace agl::utl {  // temp because this namespace doesn't exist in the sead decomp yet, remove
> ```

This should be in a separate header in `agl` (and PR'd to the agl repository separately).
___
*[`src/KingSystem/System/VideoRecorder.h` line 40 at r1](https://reviewable.io/reviews/zeldaret/botw/98#-N7SAV2K84zl0hPZF-xp:-N7SAV2K84zl0hPZF-xq:bowllen) ([raw file](https://github.com/zeldaret/botw/blob/954e4d28a25edd2cad0e1fc745dfae490c300dcf/src/KingSystem/System/VideoRecorder.h#L40)):*
> ```objc
> 
> public:
>     u64 reserveCaptureWithDebugHeap(bool somebool, u64 someint, const sead::SafeString*,
> ```

This doesn't have the correct signature according to the symbol.

`agl::utl::ScreenShotMgr::reserveCaptureWithDebugHeap(bool,agl::TextureDataSerializerTGA::TGAFormat,sead::SafeStringBase<char> const&,bool)`

This should be:

```
void reserveCaptureWithDebugHeap(bool unk, agl::TextureDataSerializerTGA::TGAFormat format, const sead::SafeString& output_path, bool unk2);
```

void because the function doesn't actually appear to return anything.
___
*[`src/KingSystem/System/VideoRecorder.cpp` line 7 at r1](https://reviewable.io/reviews/zeldaret/botw/98#-N7S9u1I0OHsy2T-fP2Q:-N7S9u1I0OHsy2T-fP2R:b-rfo741) ([raw file](https://github.com/zeldaret/botw/blob/954e4d28a25edd2cad0e1fc745dfae490c300dcf/src/KingSystem/System/VideoRecorder.cpp#L7)):*
> ```cpp
> 
> void VideoRecorder::postCalc() {
>     if (isCaptureEnabled()) {
> ```

```
if (!isCaptureEnabled())
    return;
```

https://llvm.org/docs/CodingStandards.html#use-early-exits-and-continue-to-simplify-code
___
*[`src/KingSystem/System/VideoRecorder.cpp` line 8 at r1](https://reviewable.io/reviews/zeldaret/botw/98#-N7SA3q88DPnnVJEMnZF:-N7SA3q88DPnnVJEMnZG:b-zekf2h) ([raw file](https://github.com/zeldaret/botw/blob/954e4d28a25edd2cad0e1fc745dfae490c300dcf/src/KingSystem/System/VideoRecorder.cpp#L8)):*
> ```cpp
> void VideoRecorder::postCalc() {
>     if (isCaptureEnabled()) {
>         u32 framenum = frame_number;  // not sure why a new variable is created instead of using
> ```

This comment should also be removed. Code should generally look like a developer would have actually written, and this isn't strange enough to warrant a "this is odd" comment.


<!-- Sent from Reviewable.io -->

2022-07-20 19:59 UTC, leoetlino requested changes
> Reviewed 1 of 4 files at r1.
> *[Reviewable](https://reviewable.io/reviews/zeldaret/botw/98)* status: all files reviewed, 10 unresolved discussions (waiting on @ecumber)

___
*[`src/KingSystem/System/VideoRecorder.h` line 29 at r1](https://reviewable.io/reviews/zeldaret/botw/98#-N7SBNIy3Uv3liSCgisM:-N7SBNIy3Uv3liSCgisN:beb3oyf) ([raw file](https://github.com/zeldaret/botw/blob/954e4d28a25edd2cad0e1fc745dfae490c300dcf/src/KingSystem/System/VideoRecorder.h#L29)):*
> ```objc
> 
> KSYS_CHECK_SIZE_NX150(VideoRecorder, 0x148);
> }  // namespace ksys
> ```

There should be another line break before the closing brace.
___
*[`src/KingSystem/System/VideoRecorder.cpp` line 3 at r1](https://reviewable.io/reviews/zeldaret/botw/98#-N7SBFhc4LqjQ_ch1mdi:-N7SBFhc4LqjQ_ch1mdj:b-6rpvpn) ([raw file](https://github.com/zeldaret/botw/blob/954e4d28a25edd2cad0e1fc745dfae490c300dcf/src/KingSystem/System/VideoRecorder.cpp#L3)):*
> ```cpp
> #include "KingSystem/System/VideoRecorder.h"
> 
> namespace ksys {
> ```

There should be another line break after the opening brace.
___
*[`src/KingSystem/System/VideoRecorder.cpp` line 16 at r1](https://reviewable.io/reviews/zeldaret/botw/98#-N7SBJcR9T9yIYza4Ryd:-N7SBJcR9T9yIYza4Rye:beb3oyf) ([raw file](https://github.com/zeldaret/botw/blob/954e4d28a25edd2cad0e1fc745dfae490c300dcf/src/KingSystem/System/VideoRecorder.cpp#L16)):*
> ```cpp
>     }
> }
> }  // namespace ksys
> ```

There should be another line break before the closing brace.


<!-- Sent from Reviewable.io -->

2022-07-23 15:06 UTC, leoetlino approved these changes
LGTM, this should be good to go after the build and lint errors are fixed

> Reviewed 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/zeldaret/botw/98#-:-N7fa4tw5Orumam9YP0P:bdulhbl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ecumber)



<!-- Sent from Reviewable.io -->

2022-07-24 14:23 UTC, leoetlino commented
Build still appears to be falling. It looks like you might need to include seadSafeString.h in that agl header – my bad for not catching the issue in the agl PR.

2022-07-24 22:30 UTC, leoetlino reviewed
The lib/agl submodule is pointing to the wrong commit -- make sure it's pointing to the master branch of open-ead/agl, not your fork

> Reviewed 2 of 3 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/zeldaret/botw/98#-:-N7mK99z-q-xivq9z-s_:b-5ejnaz)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ecumber)



<!-- Sent from Reviewable.io -->

2022-07-25 05:06 UTC, ecumber commented
Should be good to go now

2022-07-25 09:09 UTC, leoetlino approved these changes
> Reviewed 2 of 2 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/zeldaret/botw/98)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ecumber)



<!-- Sent from Reviewable.io -->

2022-07-25 09:09 UTC, merged